.TH rct 8 "November 8, 2012" "version 1.0" "Certificate Information Tool"  Deon Lackey 
.SH NAME
rct \- Displays information (headers) about or size and statistics of a entitlement, product, or identity certificate used by Red Hat Subscription Manager.

.SH SYNOPSIS
rct cat-cert [--no-content] [--no-products] /path/to/certificate.pem
rct stat-cert /path/to/certificate.pem

.SH DESCRIPTION
Red Hat Subscription Manager uses X.509 certificates to identify a registered system (identity certificate), the products installed on that system (product certificates), and the subscriptions attached to the system (entitlement certificates), including available content repositories, products, and support levels. All of the information that Subscription Manager requires is contained in the body of the certificate.

.PP

.SH COMMANDS
.TP
.B stat-cert
Prints the size of the certificate and other details about the certificate. The precise details depend on the type of certificate being checked.

.TP
.B cat-cert
Sets the interval to use between checks for the product subscription status. The value is in seconds. Two options, \fB--no-content\fP and \fB--no-products\fP, can be used to shorten the output to include only header and descriptive information.

.SH THE STAT-CERT COMMAND
The \fBrct\fP tool is used to gather information about the already-issued certificates being used by Subscription Manager. The main reason for that is that certificate sizes, for a number of reasons, impact content delivery service performance. New certificate version (3.0 and later) use more efficient encoding, resulting in smaller certificate content sizes and better performance. If there are problems with the content service timing out or returning errors, then the \fBrct stat-cert\fP command can be used to check the size and version of a given entitlement certificate quickly.

.PP
This command has no options.

.PP
For large accounts and organizations, there can be a very large number of products and content sets available. Older versions of entitlement certificates (version 1.0) used different (less efficient) DER encoding, so that large amounts of information results in very large certificates. (This is what caused timeouts or crashes when dealing with some content services.) Newer entitlement certificate versions (version 3.0) use more efficient encoding on large content sets, which improves overall subscription service performance.

.PP 
A large number of content sets is anything over 185 total sets. Both the total number of content sets and the size of the DER encoding in the certificate could affect performance.

.PP 
The statistics for an entitlement certificate show both the DER size and the number of content sets, among other information:
* Type (entitlement certificate)
.IP
* Version (of the certificate style); newer versions will be 3.x, with better performance for handling large content sets
.IP
* DER size, which gives the size of the certificate contents (not the size of the certificate file itself)
.IP
* Key size, for the associated key file, in bytes
.IP
* The total number of available content sets in the subscription

.PP
For example:
.RS
.nf
[root@server ~]# rct stat-cert /etc/pki/entitlement/2027912482659389239.pem
Type: Entitlement Certificate
Version: 1.0
DER size: 47555b
Subject Key ID size: 553b
Content sets: 100
.fi
.RE

.PP
While the size of the certificate is less of an issue for identity and product certificates (which are quite small), the \fBstat-cert\fP command can still be used to view the size and statistics of the certificates.

.PP
For a product certificate, the \fBstat-cert\fP command shows:
.IP
* Type (product certificate)
.IP
* Version (of the certificate style)
.IP
* DER size, which gives the size of the certificate contents (not the size of the certificate file itself)

.PP
For example:
.RS
.nf
[root@server ~]# rct stat-cert /etc/pki/product/69.pem
Type: Product Certificate
Version: 1.0
DER size: 1558b
.fi
.RE

.PP
For an identity certificate:
.IP
* Type (identity certificate)
.IP
* Version (of the certificate style)
.IP
* DER size, which gives the size of the certificate contents (not the size of the certificate file itself)
.IP
* Key size, for the associated key file, in bytes

.PP
For example:
.RS
.nf
[root@server ~]# rct stat-cert /etc/pki/consumer/cert.pem
Type: Identity Certificate
Version: 1.0
DER size: 1488b
Subject Key ID size: 20b
.fi
.RE

.SH CAT-CERT COMMAND
Each certificate contains a complete set of information that contains all of the details for whatever element is being identified. That information can be displayed, in pretty-print form, using the \fBcat-cert\fP command.

.PP
The most basic information is the information about the certificate its, such as its directory path, its serial umber and subject name, and its validity period (start and end dates). The information about the certificate itself is in the \fICertificate\fP section:
.IP
* Path -- the filesystem location where the certificate is installed
.IP
* Version -- the certificate format version
.IP
* Serial -- the serial number for the certificate
.IP
* Start/End Date -- the validity period for the certificate
.IP
* Alt Name -- the subject alternative name, which uses the hostname of the system rather than the UUID (for identity certificates only)
.PP
The Subject DN of the certificate is in the \fISubject\fP section.

.PP
For example, for the identity certificate:
.RS
.nf
[root@server ~]# rct cat-cert /etc/pki/consumer/cert.pem

+-------------------------------------------+
        Identity Certificate
+-------------------------------------------+

Certificate:
        Path: /etc/pki/consumer/cert.pem
        Version: 1.0
        Serial: 824613308750035399
        Start Date: 2012-11-09 16:20:22+00:00
        End Date: 2013-11-09 16:20:22+00:00
        Alt Name: DirName:/CN=server.example.com

Subject:
        CN: e94bc90e-44a1-4f8c-b6fc-0a3e9d6fac2b
.fi
.RE

.PP
A product certificate contains additional information in a \fBProduct\fP section, which defines the information for the specific installed product, such as its name, product version, and any yum tags used for that product. For example:
.RS
.nf
[root@server ~]# rct cat-cert /etc/pki/product/69.pem

+-------------------------------------------+
        Product Certificate
+-------------------------------------------+

Certificate:
        Path: /etc/pki/product/69.pem
        Version: 1.0
        Serial: 12750047592154746449
        Start Date: 2012-10-04 18:45:02+00:00
        End Date: 2032-09-29 18:45:02+00:00

Subject:
        CN: Red Hat Product ID [b4f7ac9e-b7ed-45fa-9dcc-323beb20e916]

Product:
        ID: 69
        Name: Red Hat Enterprise Linux Server
        Version: 6.4
        Arch: x86_64
        Tags: rhel-6,rhel-6-server
.fi
.RE

.PP
The most information is contained in the entitlement certficate. Along with the \fBCertificate\fP and \fBSubject\fP, it also has a \fBProduct\fP section that defines the product group that is covered by the subscription. 
.PP
Then, it contains an \fBOrder\fP section that details everything related to the purchase of the subscription (such as the contract number, service level, total quantity, quantities assigned to the system, and other details on the subscription). 
.PP
A subscription for a product covers the version purchased \fIand\fP every previous version of the product. For example, when a subscription is purchased for Red Hat Enterprise Linux 6.4, the subscription provides full access to all RHEL 6 repositories, \fBplus\fP access to all RHEL 5 repositories and then other included product content repositories, like Subscription Asset Manager. Every available content repository is lised in a \fBContent\fP section that contains the repository name, associated tags, its URL, and a notice on whether the yum repository is enabled by default. For example:
.RS
.nf
[root@server ~]# rct cat-cert /etc/pki/entitlement/2027912482659389239.pem  
+-------------------------------------------+
        Entitlement Certificate
+-------------------------------------------+

Certificate:
        Path: /etc/pki/entitlement/2027912482659389239.pem
        Version: 1.0
        Serial: 2027912482659389239
        Start Date: 2011-12-31 05:00:00+00:00
        End Date: 2012-12-31 04:59:59+00:00

Subject:
        CN: 8a99f9843adc8b8f013ae5f9de022b73

Product:
        ID: 69
        Name: Red Hat Enterprise Linux Server
        Version:
        Arch: x86_64,ia64,x86
        Tags:

Order:
        Name: Red Hat Enterprise Linux Server, Premium (8 sockets) (Up to 4 guests)
        Number: 2673502
        SKU: RH0103708
        Contract: 10011052
        Account: 5206751
        Service Level: Premium
        Service Type: L1-L3
        Quantity: 100
        Quantity Used: 1
        Socket Limit: 8
        Virt Limit:
        Virt Only: False
        Subscription:
        Stacking ID:
        Warning Period: 0
        Provides Management: 0

Content:
        Type: yum
        Name: Red Hat Enterprise Linux 6 Server (RPMs)
        Label: rhel-6-server-rpms
        Vendor: Red Hat
        URL: /content/dist/rhel/server/6/$releasever/$basearch/os
        GPG: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        Enabled: True
        Expires: 86400
        Required Tags: rhel-6-server
....
.fi
.RE
.PP
Using the \fB--no-content\fP option when running \fBrct cat-cert\fP with an entitlement certificate returns all of the certification information, order information, and product information, but excludes all of the \fBContent\fP sections, which significantly reduced the information printed to stdout. If there are a lot of \fBProduct\fP sections, as well, then those can be excluded using the \fB--no-product\fP option.

.SH FILES
.IP
* Product certificates: /etc/pki/product/*.pem
.IP
* Subscription certificates: etc/pki/entitlement/<serial#>.pem
.IP
* System identity certificates: /etc/pki/consumer/cert.pem

.SH BUGS
This tool is part of Red Hat Subscription Manager. To file bugs against this command-line tool, go to <https://bugzilla.redhat.com>, and select Red Hat > Red Hat Enterprise Linux > subscription-manager.


.SH AUTHORS
Deon Lackey <dlackey@redhat.com>, Michael Stead <mstead@redhat.com>, and James Bowes <jbowes@redhat.com>. The rct tool was written by James Bowes.

.SH COPYRIGHT
Copyright (c) 2012 Red Hat, Inc. This is licensed under the GNU General Public License, version 2 (GPLv2). A copy of this license is available at http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
