.\" Copyright 2011 Red Hat, Inc.
.\"
.\" This man page is free documentation; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this man page; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH "rhn-migrate-classic-to-rhsm" "8" "September 5, 2012" "Version 0.5" ""

.SH NAME

rhn-migrate-classic-to-rhsm \- Migrates a system profile from Red Hat Network Classic Hosted to Customer Portal Subscription Management (hosted) or Subscription Asset Manager (on-premise).

.SH SYNOPSIS
rhn-migrate-classic-to-rhsm [--force | --gui | --no-auto | --servicelevel=SERVICE_LEVEL | --serverurl=URL | --help]

.SH DESCRIPTION
\fBrhn-migrate-classic-to-rhsm\fP migrates a system profile which is registered with Red Hat Network Classic to Customer Portal Subscription Management. This is intended for migrating from the host service, not for migrating from a Satellite system.

.PP
This script migrates configuration, from a channel-based subscription framework to a certificate-based subscription framework. While the \fBrhn-migrate-classic-to-rhsm\fP script performs the migration operation, the data used to map the channels to the corresponding product certificates is defined in the \fBsubscription-manager-migration-data\fP package. The \fBsubscription-manager-migration-data\fP package must be installed before the \fBrhn-migrate-classic-to-rhsm\fP script can be run successfully.

.SH BACKGROUND
Access to support and updates for products is determined through 
.I subscriptions.
Subscriptions are assigned to a system, which means that the system has the right to install and update a product with full support. Subscriptions for an entire organization are tracked through a 
.I subscription service.

.PP
With the channel-based framework, a subscription service was either a local Satellite or hosted Red Hat Network Classic. With the new certificate-based subscriptions, the subscription service is either Customer Portal Subscription Management or Subscription Asset Manager. The differences between the two types of subscription services are described in this Knowledgebase article: <https://access.redhat.com/kb/docs/DOC-45987>

.PP
The system registers with the subscription service and receives an inventory ID number. When subscriptions are applied to a system, that association is noted in the subscription service. 

.PP
Registering with a subscription service is exclusive. If a system is registered with Red Hat Network Classic, it cannot simultaneously be registered with Customer Portal Subscription Management. The 
.B rhn-migrate-classic-to-rhsm
tool is provided specifically so that there is a way to transition from the deprecated Red Hat Network Classic to Customer Portal Subscription Management or a local Subscription Asset Manager.

.SH OPTIONS
.TP
.B -h, --help
Prints the specific help information for the given command.

.TP
.B -f, --force
Ignore channels not available through Customer Portal Subscription Management (or Subscription Asset Manager). The channels in Red Hat Network Classic are mapped to the product certificates used by the Customer Portal Subscription Management. However, not every channel has a certificate mapping, which can cause errors during migration. Using this option skips any channels which are not mapped to Customer Portal Subscription Management.

.TP
.B -g, --gui
Opens the Subscription Manager UI so that administrators can manually select which subscriptions to apply to the 
system rather than automatically applying best-matched subscriptions based on the existing channel subscriptions.

.TP
.B -n, --no-auto
Unsubscribes the system from Red Hat Network Classic and registers it to Customer Portal Subscription Management, but does not subscribe the system to any subscriptions.

.TP
.B -s SERVICE_LEVEL, --servicelevel=SERVICE_LEVEL
Sets a preferred service level for the system, such as premium or standard. This service level preference is then used as one of the criteria for autosubscribing the system.

.TP
.B --serverurl=URL
Gives the URL of the subscription management service to which to register the system. This is used for environments which have an on-premise subscription service such as Subscription Asset Manager. If no URL is given, the migration tool uses the Customer Portal Subscription Management Service. 

.SH USAGE
The migration process moves the system from the inventory in one subscription service (Red Hat Network Classic) to the new subscription service (Customer Portal Subscription Management), and then re-applies the subscriptions to the system. The script runs through these steps:

.IP
1. Authenticate to both Red Hat Network Classic and Customer Portal Subscription Management to verify the account settings.

.IP
2. Get a channel list for the system.

.IP
3. Match each channel to a corresponding certificate map.

.IP
4. Copy over the product certificates for the old channels.

.IP
5. Unregister from Red Hat Network Classic.

.IP
6. Register with Customer Portal Subscription Management and auto-subscribe to the best-matched subscriptions. (Alternatively, the 
.B --gui
option can be used to launch the Subscription Manager UI to assign subscriptions manually.)

.PP
After migration, the system facts maintained by Subscription Manager display what script was used for migration and what the previous system ID was. 
.nf
[root@server ~]# subscription-manager facts --list | grep migr
migration.classic_system_id: 09876
migration.migrated_from: rhn_hosted_classic
migration.migration_date: 2012-09-14T14:55:29.280519

.fi

.SS MIGRATION AND AUTOSUBSCRIBE
The \fBrhn-migrate-classic-to-rhsm\fP tool, by default, autosubscribes the system to the best-matching subscriptions. This allows migrations to be automated.

.nf
[root@server ~]# rhn-migrate-classic-to-rhsm
RHN Username: jsmith@example.com
Password:

Retrieving existing RHN classic subscription information ...
+----------------------------------+
System is currently subscribed to:
+----------------------------------+
rhel-i386-client-5

List of channels for which certs are being copied
rhel-i386-client-5

Product Certificates copied successfully to /etc/pki/product !!

Preparing to unregister system from RHN classic ...
System successfully unregistered from RHN Classic.

Attempting to register system to RHN ...
The system has been registered with id: abcd1234
System 'server.example.com' successfully registered to RHN.

Attempting to auto-subscribe to appropriate subscriptions ...
Installed Product Current Status:
ProductName:            Red Hat Enterprise Linux Desktop
Status:                 Subscribed

Successfully subscribed.

Please visit https://access.redhat.com/management/consumers/abcd1234 to view the details, and to make changes if necessary.
.fi

.PP
The script prompts for a username and password to use to register the system; this same account is used to authenticate with both Red Hat Network Classic and Customer Portal Subscription Management.

.PP
Optionally, the \fB--servicelevel\fP argument sets an SLA preference to use with the system. The SLA associated with a subscription is then evaluated when determining what subscriptions to autosubscribe the system to, along with other factors like installed products, existing channel assignments, and architecture.

.nf
[root@server ~]# rhn-migrate-classic-to-rhsm --servicelevel=premium
RHN Username: jsmith@example.com
Password:
.fi

.SS MIGRATION TO ON-PREMISE SERVICES
The \fBrhn-migrate-classic-to-rhsm\fP tool migrates the system to Customer Portal Subscription Management (hosted) services by default. This uses the default configuration for Subscription Manager, which points to the subscription services for the Customer Portal. For infrastructures which have an on-premise subscription management service such as Subscription Asset Manager, this configuration can be changed so that the migration process registers and subscribes the systems to the on-premise subscription services. 

.PP
This is done by using the \fB--serverurl\fP option, which specifies the URL of the local service. In this case, the authorization credentials must also be given for the local subscription management service account (which is independent of the RHN account).

.nf
[root@server ~]# rhn-migrate-classic-to-rhsm --serverurl=sam.example.com
Username: jsmith@example.com
Password:
.fi

.SS MIGRATION AND MANUALLY SELECTING SUBSCRIPTIONS
The \fB--no-auto\fP option prevents the autosubscribe step from running. The \fB--gui\fP option not only prevents autosubscribe from running, it automatically opens the Subscription Manager GUI so that administrators can assign subscriptions to the system.

.PP
As with the autosubscribe process, the script prompts for the RHN username and password for the user.

.nf
[root@server ~]# rhn-migrate-classic-to-rhsm --gui 
RHN Username: jsmith@example.com
Password:

Retrieving existing RHN classic subscription information ...
+----------------------------------+
System is currently subscribed to:
+----------------------------------+
rhel-i386-client-5

List of channels for which certs are being copied
rhel-i386-client-5

Product Certificates copied successfully to /etc/pki/product !!

Preparing to unregister system from RHN classic ...
System successfully unregistered from RHN Classic.

Attempting to register system to RHN ...
The system has been registered with id: abcd1234
System server.example.com successfully registered to RHN.

Launching the GUI tool to manually subscribe the system ...
.fi

.SH FILES

.IP \fI/etc/sysconfig/rhn/systemid\fP
The digital server ID for this machine if the system has been registered with Red Hat Network Classic. 
This file does not exist otherwise.

.IP \fI/etc/sysconfig/rhn/up2date\fP
The common configuration file used by RHN client programs.

.IP \fI/var/log/rhsm/rhsm.log\fP
The Subscription Manager log file. This contains any errors registering the system to Customer Portal Subscription Management or with subscribing the system to subscriptions.

.IP \fBsubscription-manager-migration-data.rpm\fB
The package which contains the mappings for the migration script to migrate channels to the appropriate product certificates.

.SH SEE ALSO
\fBinstall-num-migrate-to-rhsm\fP(8), \fBsubscription-manager\fP(8).


.SH AUTHORS
.PP
Deon Lackey <dlackey@redhat.com>, Paresh Mutha <pmutha@redhat.com>, Mark Huth <mhuth@redhat.com>, Tasos Papaioannou <tpapaioa@redhat.com>

.SH BUGS
.PP
Report bugs to <http://bugzilla.redhat.com>.

.SH COPYRIGHT

.PP
Copyright \(co 2012 Red Hat, Inc.

.PP
This is free software; see the source for copying conditions.  There is 
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
