'\" t
.\"     Title: rhsm.conf
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/07/2014
.\"    Manual: \ \&
.\"    Source: rhsm.conf
.\"  Language: English
.\"
.TH "RHSM\&.CONF" "5" - "rhsm\&.conf" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rhsm.conf \- Configuration file for the subscription\-manager tooling
.SH "DESCRIPTION"
.sp
The rhsm\&.conf file is the configuration file for various subscription manager tooling\&. This includes \fBsubscription\-manager\fR, \fBsubscription\-manager\-gui\fR, \fBrhsmcertd\fR, and \fBvirt\-who\fR\&.
.SH "[SERVER] OPTIONS"
.PP
hostname
.RS 4
The hostname of the subscription service being used\&. The default is the Red Hat Customer Portal which is subscription\&.rhsm\&.redhat\&.com\&.
This default should not be retrofitted to previously installed versions\&. It should be incorporated as the default going forward\&.
.RE
.PP
prefix
.RS 4
Server prefix where the subscription service is registered\&.
.RE
.PP
port
.RS 4
The port which the subscription service is listening on\&.
.RE
.PP
insecure
.RS 4
This flag enables or disables entitlement server certification verification using the certificate authorities which are installed in /etc/rhsm/ca\&.
.RE
.PP
ssl_verify_depth
.RS 4
Sets the number of certificates which should be used to verify the servers identity\&. This is an advanced control which can be used to secure on premise installations\&.
.RE
.PP
server_timeout
.RS 4
Set this to a non\-blank value to override the HTTP timeout in seconds\&. The default is 180 seconds (3 minutes)\&.
.RE
.PP
proxy_hostname
.RS 4
Set this to a non\-blank value if
\fBsubscription\-manager\fR
should use a reverse proxy to access the subscription service\&. This sets the host for the reverse proxy\&. Overrides hostname from \fBHTTP_PROXY\fR and \fBHTTPS_PROXY\fR environment variables\&. This value
.B should not
contain the scheme to be used with the proxy (e.g. http or https)\&. To specify that use the
.B proxy_scheme
option\&.
.RE
.PP
proxy_scheme
.RS 4
This sets the scheme for the reverse proxy when writing out the proxy to repo definitions\&. Set this to a non\-blank value if you want to specify the scheme used by your package manager for subscription\-manager managed repos\&. This defaults to "http"\&.
.RE
.PP
proxy_port
.RS 4
Set this to a non\-blank value if
\fBsubscription\-manager\fR
should use a reverse proxy to access the subscription service\&. This sets the port for the reverse proxy\&. Overrides port from \fBHTTP_PROXY\fR and \fBHTTPS_PROXY\fR environment variables\&.

Please note that setting this to any value other than 3128 (depending on your SELinux configuration) will require an update to that policy.

To add a local policy:

# semanage port -a -t squid_port_t -p tcp <port number>

To change the system back to look at 3128 port, just remove the policy:

# semanage port -d -t squid_port_t -p tcp <port number>
.RE
.PP
proxy_username
.RS 4
Set this to a non\-blank value if
\fBsubscription\-manager\fR
should use an authenticated reverse proxy to access the subscription service\&. This sets the username for the reverse proxy\&. Overrides username from \fBHTTP_PROXY\fR and \fBHTTPS_PROXY\fR environment variables\&.
.RE
.PP
proxy_password
.RS 4
Set this to a non\-blank value if
\fBsubscription\-manager\fR
should use an authenticated reverse proxy to access the subscription service\&. This sets the password for the reverse proxy\&. Overrides password from \fBHTTP_PROXY\fR and \fBHTTPS_PROXY\fR environment variables\&.
.RE
.PP
no_proxy
.RS 4
Set this to a non\-blank value if
\fBsubscription-manager\fR
should not use a proxy for specific hosts\&. Format is a comma-separated list of hostname suffixes,
optionally with port\&. '*' is a special value that means do not use a proxy for any host\&. Overrides the \fBNO_PROXY\fR environment variable\&.
.RE
.SH "[RHSM] OPTIONS"
.PP
baseurl
.RS 4
This setting is the prefix for all content which is managed by the subscription service\&. This should be the hostname for the Red Hat CDN, the local Satellite or Capsule depending on your deployment\&.
Prefix depends on the service type.
For the Red Hat CDN, the full
.B baseurl
is
.B https://cdn.redhat.com
\&.
For Satellite 6, the baseurl is
.B https://HOSTNAME/pulp/repos
, so for a hostname of
.B sat6.example.com
the full
.B baseurl
would be for example:
.B https://sat6.example.com/pulp/repos
\&.
.RE
.PP
repomd_gpg_url
.RS 4
The URL of the GPG key that was used to sign this repository's metadata\&. The specified GPG key will be used in addition to any GPG keys defined by the entitlement\&.
.RE
.PP
ca_cert_dir
.RS 4
The location for the certificates which are used to communicate with the server and to pull down content\&.
.RE
.PP
repo_ca_cert
.RS 4
The certificate to use for server side authentication during content downloads\&.
.RE
.PP
productCertDir
.RS 4
The directory where product certificates should be stored\&.
.RE
.PP
entitlementCertDir
.RS 4
The directory where entitlement certificates should be stored\&.
.RE
.PP
consumerCertDir
.RS 4
The directory where the consumers identity certificate is stored\&.
.RE
.PP
manage_repos
.RS 4
Set this to
\fI1\fR
if subscription manager should manage a yum repos file\&. If set, it will manage the file /etc/yum\&.repos\&.d/redhat\&.repo\&. If set to
\fI0\fR
then the subscription is only used for tracking purposes, not content\&. The /etc/yum\&.repos\&.d/redhat\&.repo file will either be purged or deleted\&.
.RE
.PP
full_refresh_on_yum
.RS 4
Set to
\fI1\fR
if the /etc/yum\&.repos\&.d/redhat\&.repo should be updated with every server command\&. This will make yum less efficient, but can ensure that the most recent data is brought down from the subscription service\&.
.RE
.PP
report_package_profile
.RS 4
Set to
\fI1\fR
if
\fBrhsmcertd\fR
should report the system's current package profile to the subscription service\&. This report helps the subscription service provide better errata notifications\&. If supported by the entitlement server, enabled repos, enabled modules, and packages present will be reported\&. This configuration also governs package profile reporting when the "dnf uploadprofile" command is executed\&.
.RE
.PP
package_profile_on_trans
.RS 4
Set to
\fI1\fR
if the
\fBdnf/yum subscription-manager plugin\fR
should report the system's current package profile to the subscription service on execution of dnf/yum transactions (for example on package install)\&. This report helps the subscription service provide better errata notifications\&. If supported by the entitlement server, enabled repos, enabled modules, and packages present will be reported\&. The \fBreport_package_profile\fR option needs to also be set to 1 for this option to have any effect.
.RE
.PP
pluginDir
.RS 4
The directory to search for subscription manager plug-ins
.RE
.PP
pluginConfDir
.RS 4
The directory to search for plug-in configuration files
.RE
.PP
auto_enable_yum_plugins
.RS 4
When this option is enabled, then yum/dnf plugins subscription-manager and product-id are enabled every-time subscription-manager or subscription-manager-gui is executed.
.RE
.PP
inotify
.RS 4
Inotify is used for monitoring changes in directories with certificates. Currently only the /etc/pki/consumer directory is monitored by the rhsm.service. When this directory is mounted using a network file system without inotify notification support (e.g. NFS), then disabling inotify is strongly recommended. When inotify is disabled, periodical directory polling is used instead.
.RE
.SH "[RHSMCERTD] OPTIONS"
.PP
certCheckInterval
.RS 4
The number of minutes between runs of the
\fBrhsmcertd\fR
daemon
.RE
.PP
autoAttachInterval
.RS 4
The number of minutes between attempts to run auto\-attach on this consumer\&.
.RE
.PP
splay
.RS 4
1 to enable splay. 0 to disable splay. If enabled, this feature delays the initial auto attach and cert check by an amount between 0 seconds and the interval given for the action being delayed. For example if the
.B certCheckInterval
were set to 3 minutes, the initial cert check would begin somewhere between 2 minutes after start up (minimum delay) and 5 minutes after start up. This is useful to reduce peak load on the Satellite or entitlement service used by a large number of machines.
.RE
.PP
disable
.RS 4
set to 1 to disable rhsmcertd operation entirely.
.SH "[LOGGING] OPTIONS"
.PP
default_log_level
.RS 4
The default log level for all loggers in subscription-manager, python-rhsm, rhsmd, and rhsmcertd.
Note: Other keys in this section will override this value for the specified logger.
.RE
.PP
MODULE_NAME[.SUBMODULE ...] = [log_level]
.RS 4
Logging can be configured on a module-level basis via entries of the format above where:
.RS 4
.B module_name
is subscription_manager, rhsm, or rhsm-app.
.PP
.B submodule
can be optionally specified to further override the logging level down to a specific file.
.PP
.B log_level
is the log level to set the specified logger (one of: DEBUG, INFO, WARNING, ERROR, or CRITICAL).
.RE
.RE
.SH "AUTHOR"
.sp
Bryan Kearney <bkearney@redhat\&.com>
.SH "SEE ALSO"
.sp
\fBsubscription\-manager\fR(8), \fBsubscription\-manager\-gui\fR(8), \fBrhsmcertd\fR(8)
.SH "RESOURCES"
.sp
Main web site: http://www\&.candlepinproject\&.org/
.SH "COPYING"
.sp
Copyright (c) 2010\-2012 Red Hat, Inc\&. This is licensed under the GNU General Public License, version 2 (GPLv2)\&. A copy of this license is available at http://www\&.gnu\&.org/licenses/old\-licenses/gpl\-2\&.0\&.txt\&.
