.TH rct 8 "May 23, 2013" "version 1.3" "Certificate Information Tool"  Deon Lackey
.SH NAME
rhsm-debug \- Compiles information about consumer's entitlements, products, and identity used by Red Hat Subscription Manager.

.SH SYNOPSIS
rhsm-debug compile  [--destination /path] /path/to/system-debug.zip

.SH DESCRIPTION

.PP

.SH COMMANDS
.TP
.B compile


.PP


.SS OPTIONS
.TP

.SS EXAMPLES



.SH BUGS
This tool is part of Red Hat Subscription Manager. To file bugs against this command-line tool, go to <https://bugzilla.redhat.com>, and select Red Hat > Red Hat Enterprise Linux > subscription-manager.


.SH AUTHORS
William Poteat<wpoteat@redhat.com>. The rhsm-debug tool was written by William Poteat.

.SH COPYRIGHT
Copyright (c) 2012 Red Hat, Inc. This is licensed under the GNU General Public License, version 2 (GPLv2). A copy of this license is available at http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
