.TH subscription-manager 8 "" "" "Subscription Management"
.SH NAME
subscription-manager \- Registers systems to a subscription management service, reports system facts, and manages various configurations to the entitled content repositories granted by the subscription management services.

.SH SYNOPSIS
.B subscription-manager
.I COMMAND
[
.I SUBCOMMAND
] [
.I OPTIONS
]

.SH DESCRIPTION
The
.B subscription-manager
program (also known as Red Hat Subscription Manager) is a client tool that can be used to register a system with a subscription management service such as the Red Hat Customer Portal, or an on-premise solution such as Red Hat Satellite.
.PP
Red Hat provides content updates and support by issuing
.I subscriptions
for its products. When a system is registered, factual data about the system's hardware are uploaded to the subscription management services. The services use the factual data to generate entitlements from the organization's available product subscriptions and appropriately grant them to the system. Once applied, the registering system can install, update, and receive support for the subscribed software products.


.SH COMMANDS, SUBCOMMANDS, AND OPTIONS
This section details all available commands, subcommands, and their optional parameters. Common options shared across multiple commands are documented at the end of this section, along with information on interactive prompting for required authentication parameters.
.PP
.SS REGISTER OPTIONS
The
.B register
command registers a new system to the subscription management service.

.TP
.B --username=USERNAME
Gives the username for the account which is registering the system; this user account is usually tied to an organization with ownership access to a content delivery system which supplies subscription content. This option is required for user-based authentication, but not key-based authentication.

.TP
.B --password=PASSWORD
Gives the user account password.

.TP
.B --serverurl=SERVER_HOSTNAME:PORT/PREFIX
Specifies the URL of the subscription management service used to register the system. By default, this points to the Red Hat Customer Portal Subscription Management service (https://\:subscription.rhsm.redhat.com:443/\:subscription).
.RS
.PP
You can use this parameter to point to a custom or local subscription service. However, using this parameter alone is discouraged, as additional configuration settings are usually required for proper operation.
.PP
.B Note:
If you are registering to an on-premise service such as Red Hat Satellite, install the katello-ca-consumer RPM instead. Installing this RPM is more reliable because it automatically sets all required configuration parameters and installs the necessary CA certificates to ensure a secure SSL connection.
.RE

.TP
.B --baseurl=https://CONTENT_SERVICE:PORT/PREFIX
Specifies the URL of the content delivery service used by dnf to download packages. By default, this points to the Red Hat CDN (https://\:cdn.redhat.com).
.RS
.PP
You can use this parameter to specify a different content delivery network when registering to a custom subscription service. However, using this parameter alone is discouraged, as other configuration settings must also be updated to ensure the system is properly configured.
.PP
.B Note:
If you are registering to an on-premise service such as Red Hat Satellite, install the katello-ca-consumer RPM instead. Installing this RPM is more reliable because it automatically sets all required configuration parameters and installs the necessary CA certificates to ensure a secure SSL connection.
.RE

.TP
.B --insecure
Do not check the server SSL certificate against available certificate authorities.

.TP
.B --name=SYSTEM_NAME
Sets the name of the system to register. This defaults to the hostname.


.TP
.B --consumerid=CONSUMERID
References an existing system inventory ID to resume using a previous registration for this system. The ID is used as an inventory number for the system in the subscription management service database. If the system's identity is lost or corrupted, this option allows it to resume using its previous identity and subscriptions.

.TP
.B --activationkey=KEYS
Gives a comma-separated list of product keys to apply specific subscriptions to the system. This is used for preconfigured systems which may already have products installed. Activation keys are issued by an on-premise subscription management service, such as Satellite.
.IP
When the
.B --activationkey
option is used in conjunction with the
.B --org
option, then
.B --username
and
.B --password
are not needed because the authentication information is implicit in the activation key.
.IP
For example:
.RS
.nf
subscription-manager register --org="IT Dept" --activationkey=it_key
.fi
.RE

.TP
.B --force
When the system is already registered, a new attempt to register will fail with a message reminding the user that the system is already registered. For that reason, passing the
.B --force,
option is a convenient way to implicitly unregister the system first.
.PP
.RS
.B Note:
Specifying the
.B --force
option does not guarantee a successful registration.  For example, if the registration with
.B --force
includes a different
.B --serverurl
than was used for the original registration, the implicit call to unregister from the original entitlement server will fail with invalid credentials and the registration with force will be aborted.  In this case, the user should explicitly unregister from the original entitlement server. If unregistering is not possible, then running subscription-manager clean will effectively abandon the original registration identity and entitlements.  Once cleaned, registering a new system identity should succeed with or without force.
.RE

.TP
.B --org=ORG
Assigns the system to an organization. Infrastructures which are managed on-site may be
.I multi-tenant,
meaning that there are multiple organizations within one customer unit. A system may be assigned manually to one of these organizations. When a system is registered with the Customer Portal, this is not required. When a system is registered with an on-premise subscription service such as Red Hat Satellite, this argument
.I is
required, unless there is only a single organization configured.

.TP
.B --environments=ENV
Registers the system to one or more environments within an organization. This is a comma-separated list and the order is maintained.

.TP
.B --release=VERSION
This register option is a shortcut for the command option
.B release --set=VERSION


.SS UNREGISTER OPTIONS
The
.B unregister
command does two important things. Firstly, it will remove all of the entitlement certificates granted to the system thereby returning all consumed quantities of entitlements back to their subscription pools making them available for other registered systems within the organization. Secondly, it will remove the system's consumer identity thereby removing its connection with the subscription management service. Once unregistered, the system will no longer be entitled to system content updates from the configured subscription management service.
.PP
This command has no unique options.


.SS SYSPURPOSE OPTIONS
The
.B syspurpose
command displays the current configured syspurpose
.I preferences
for the system.

.TP
.B --show
Shows the system's current set of syspurpose preference formatted as JSON. Single-valued entries for which there is no value will be included in the output with a value of "". List entries which have no value will be included in the output with a value of "[]" (less the quotes).

.PP
The
.B syspurpose
command also has subcommands for all the various syspurpose preferences and attributes:

.IP \(bu 2
.B role

.IP \(bu 2
.B service-level

.IP \(bu 2
.B usage


.SS SYSPURPOSE ROLE OPTIONS
The
.B role
subcommand displays the current configured role
.I preference
for products installed on the system. For example, if the role preference is "Red Hat Enterprise Linux Server", then a subscription with a "Red Hat Enterprise Linux Server" is counted by subscription utilization reporting services.

.TP
.B --show
Shows the system's current role preference. If a role is not set, then there is a message saying it is not set.

.TP
.B --list
Lists the available system purpose role preferences.

.TP
.B --username=USERNAME
Gives the username for the account to use to connect to the organization account [Usable with --list on unregistered systems].

.TP
.B --password=PASSWORD
Gives the user account password [Usable with --list on unregistered systems].

.TP
.B --org=ORG
Identifies the organization for which the role applies [Usable with --list on unregistered systems].

.TP
.B --set=ROLE
Role to apply to this system

.TP
.B --unset
Removes any previously set role preference.


.SS SYSPURPOSE SERVICE-LEVEL OPTIONS
The
.B service-level
subcommand displays the current configured service level
.I preference
for products installed on the system. For example, if the service-level preference is standard, then a subscription with a standard service level is counted by subscription utilization reporting services.

.TP
.B --serverurl=SERVER_URL
Server URL in the form of https://hostname:port/prefix [Usable on unregistered systems].

.TP
.B --insecure
Do not check the server SSL certificate against available certificate authorities.

.TP
.B --show
Shows the system's current service-level preference. If a service level is not set, then there is a message saying it is not set.

.TP
.B --list
Lists the available system purpose service level preferences.

.TP
.B --username=USERNAME
Gives the username for the account to use to connect to the organization account [Usable with --list on unregistered systems].

.TP
.B --password=PASSWORD
Gives the user account password [Usable with --list on unregistered systems].

.TP
.B --set=SERVICE_LEVEL
Service level to apply to this system

.TP
.B --unset
Removes any previously set service-level preference.


.SS SYSPURPOSE USAGE OPTIONS
The
.B usage
subcommand displays the current configured usage
.I preference
for products installed on the system. For example, if the usage preference is "Production", then a subscription with a "Production" usage is counted by subscription utilization reporting services.

.TP
.B --show
Shows the system's current usage preference. If a usage is not set, then there is a message saying it is not set.

.TP
.B --list
Lists the available system purpose usage preferences.

.TP
.B --username=USERNAME
Gives the username for the account to use to connect to the organization account [Usable with --list on unregistered systems].

.TP
.B --password=PASSWORD
Gives the user account password [Usable with --list on unregistered systems].

.TP
.B --org=ORG
Identifies the organization for which the usage applies [Usable with --list on unregistered systems].

.TP
.B --set=USAGE
Usage to apply to this system

.TP
.B --unset
Removes any previously set usage preference.


.SS RELEASE OPTIONS
The
.B release
command sets a sticky OS version to use when installing or updating packages. This sets a preference for the minor version of the OS, such as 10.2 or 10.3. This can prevent unplanned or unsupported operating system version upgrades when an IT environment must maintain a certified configuration.

.TP
.B --list
Lists the available OS versions. If a release preference is not set, then there is a message saying it is not set.

.TP
.B --set=RELEASE
Sets the minor (Y-stream) release version to use, such as 10.3.

.TP
.B --unset
Removes any previously set release version preference.


.SS REPOS OPTIONS
The
.B repos
command lists all of the content repositories that are available to a system. This command is only used for organizations which have a locally-hosted content service of some kind, like Satellite. With Red Hat's hosted content service, there is only one central repository.

.TP
.B --list
Lists all of the repositories that are provided by the content service used by the system.

.TP
.B --list-enabled
Lists all of the enabled repositories that are provided by the content service used by the system.

.TP
.B --list-disabled
Lists all of the disabled repositories that are provided by the content service used by the system.

.TP
.B --enable=REPO_ID
Enables the specified repository, which is made available by the content sources identified in the system subscriptions. To enable multiple repositories, use this argument multiple times. Wild cards * and ? are supported. The repositories enabled by this option and disabled by
.B --disable
are processed in the same order they are specified.

.TP
.B --disable=REPO_ID
Disables the specified repository, which is made available by the content sources identified in the system subscriptions. To disable multiple repositories, use this argument multiple times. Wild cards * and ? are supported. The repositories disabled by this option and enabled by
.B --enable
are processed in the same order they are specified.


.SS REPO-OVERRIDE OPTIONS
The
.B repo-override
command allows the user to manage custom content repository settings

.TP
.B --repo
The repository to modify (can be specified more than once)

.TP
.B --add=NAME:VALUE
Adds a named override with the provided value to repositories specified with the
.B --repo
option

.TP
.B --remove=NAME
Removes a named override from the repositories specified with the
.B --repo
option. The override will not be removed if its source is one of the environments the system belongs in. It can only be removed by either: removing the override from the environment it originates from or removing the system from the environment the override originates from.

.TP
.B --remove-all
Removes all overrides from repositories
.B --repo
option. Overrides inherited from environments the system belongs in will not be removed. They can only be removed by either: removing them from the environment they originate from or removing the system from those environments.

.TP
.B --list
Lists all overrides from repositories specified with the
.B --repo
option. Source of the listed overrides is a union of the override specified at the system itself and all the overrides set in the environment(s) the system belongs in.


.SS LIST OPTIONS
The
.B list
command lists all of the installed products on the system. The options allow the list to be filtered.

.TP
.B --installed
Lists products which are currently installed on the system. This option is applied by default.

.TP
.B --matches=SEARCH
Limits the output of installed products which contain the SEARCH string within the product naming information. The
.br
SEARCH value may contain wildcards ? or * to match a single character or zero or more characters, respectively. The wildcard characters may be escaped with a backslash to represent a literal
question mark or asterisk. Likewise, to represent a backslash, it must be escaped with another backslash.


.SS STATUS OPTIONS
The
.B status
command shows the current status of the system.

.RS
.nf
[root@server ~]# subscription-manager status
+-------------------------------------------+
     System Status Details
+-------------------------------------------+
Overall Status: Registered
.fi
.RE
.PP
This command has no unique options.


.SS ORGS OPTIONS
The
.B orgs
command lists all of the organizations which are available to the specified user account. A multi-tenant infrastructure may have multiple organizations within a single customer, and users may be restricted to access only a subset of the total number of organizations.

.TP
.B --username=USERNAME
Gives the username for the account to use to connect to the organization account.

.TP
.B --password=PASSWORD
Gives the user account password.

.TP
.B --serverurl=SERVER_HOSTNAME:PORT/PREFIX
Passes the URL of the subscription service to use. The \fBorgs\fP command will list all organizations for which the user account is granted access. The default value is the Red Hat Customer Portal Subscription Management service. If there is an on-premise subscription service such as Satellite, this parameter can be used to submit the hostname of the subscription service, in the form \fI[protocol://]servername[:port][/prefix]\fP. If the katello-ca-consumer RPM for the Satellite is installed, then the default value configuration has been automatically updated making this parameter option unnecessary.


.SS ENVIRONMENTS OPTIONS
The
.B environments
command lists all of the environments that have been configured for an organization. This command is only used for organizations which have a locally-hosted subscription or content service of some kind, like Satellite. The concept of environments -- and therefore this command -- have no meaning for environments which use the Customer Portal Subscription Management services.

.TP
.B --username=USERNAME
Gives the username for the account to use to connect to the organization account.

.TP
.B --password=PASSWORD
Gives the user account password.

.TP
.B --org=ORG
Identifies the organization for which to list the configured environments.

.TP
.B --list
Lists all of the environments that have been configured for an organization.

.TP
.B --list-enabled
Lists the environments in the order that they have been enabled for this consumer.

.TP
.B --list-disabled
Lists all of the environments that have been configured for an organization but not enabled for this consumer.

.TP
.B --set=SET
Sets an ordered list of one or more comma-separated environments for this consumer.


.SS FACTS OPTIONS
The
.B facts
command lists the system information, like the release version, number of CPUs, and other architecture information.

.TP
.B --list
Lists all of the factual system data collected. These are simple
.I name : value
pairs that reflect much of the information in the
.B /etc/sysconfig
directory.  For example:
.PP
.RS
.nf
cpu.architecture: x86_64
cpu.core(s)_per_socket: 1
cpu.cpu(s): 2
cpu.cpu_family: 6
cpu.cpu_mhz: 1861.776
cpu.cpu_op-mode(s): 64-bit
cpu.cpu_socket(s): 2
cpu.hypervisor_vendor: KVM
cpu.model: 2
cpu.numa_node(s): 1
cpu.numa_node0_cpu(s): 0,1
cpu.stepping: 3
cpu.thread(s)_per_core: 1
cpu.vendor_id: GenuineIntel
cpu.virtualization_type: full
.fi
.RE

.TP
.B --update
Updates the system information. This is particularly important whenever there is a hardware change (such as adding a CPU) because these changes can affect the subscriptions that are compatible with the system.

.PP
.B Note:
Troublesome facts can be overridden as well as custom facts added by creating valid JSON files (named with a
.B .facts
extension) in the
.B /etc/rhsm/facts/
directory. The contents of these files must have a simple JSON format. Once created, the
.B facts --update
command should be executed.

.SS IDENTITY OPTIONS
The
.B identity
command handles the UUID of a system, which identifies the system to the subscription management service after registration. This command can simply return the UUID or it can be used to restore the registration of a previously-registered system to the subscription management service.

.TP
.B --regenerate
Requests that the subscription management service issue a new identity certificate for the system, using an existing UUID in the original identity certificate. If this is used alone, then the
.B identity
command also uses the original identity certificate to bind to the subscription management service, using certificate-based authentication.

.TP
.B --username=USERNAME
Gives the username for the account which is registering the system; this user account is usually tied to the user account for the content delivery system which supplies the content. Optional, for user-based authentication.

.TP
.B --password=PASSWORD
Gives the user account password. Optional, for user-based authentication.

.TP
.B --force
Regenerates the identity certificate for the system using username/password authentication. This is used with the
.B --regenerate
option.
.B --regenerate
alone will use an existing identity certificate to authenticate to the subscription management service. If the certificate is missing or corrupted or in other circumstances, then it may be better to use user authentication rather than certificate-based authentication. In that case, the
.B --force
option requires the username or password to be given either as an argument or in response to a prompt.


.SS REFRESH OPTIONS
The
.B refresh
command pulls the latest subscription data from the server. Normally, the system polls the subscription management service at a set interval (4 hours by default) to check for any changes in the available subscriptions. The
.B refresh
command checks with the subscription management service right then, outside the normal interval. Use of the
.B refresh
command will clear caches related to the content access mode of the system and allow the system to retrieve fresh data as necessary.

.TP
.B --force
Force regeneration of entitlement certificates on the server before these certificates are pulled from the server.


.SS CLEAN OPTIONS
The
.B clean
command forcibly removes the system's consumer identity and all local subscription entitlement data without contacting the subscription management service. Consequently, subscription entitlements assigned to this system are effectively abandoned. They will remain allocated to this system and unavailable for re-use until managed on the Customer Portal or Satellite server.

.I This command should rarely be used.
Instead, the
.B unregister
command should be your first choice when trying to reset the system registration.
.PP
The
.B clean
command is useful in cases where the local subscription information is corrupted, lost or expired. If the consumer id is still known to the subscription management service, the system can recover it's prior registered state by re-registering using the
.B register --consumerid=EXISTING_ID
command.
.PP
The most appropriate use cases for the
.B clean
command are:
.IP \(bu 2
When "Your identity certificate has expired".
.IP \(bu 2
When your system is "Unable to verify server's identity" or "Unable to make a connection using SSL client certificate." and you don't know how to recover. This can happen when incomplete attempts are made to switch your system configuration between different subscription management services.
.PP
This command has no unique options.


.SS PLUGIN OPTIONS
The
.B plugins
command lists the available subscription-manager plugins.

.TP
.B --list
List the available subscription-manager plugins.

.TP
.B --listslots
List the available plugin slots

.TP
.B --listhooks
List the available plugin slots and the hooks that handle them.

.TP
.B --verbose
Show additional info about the plugins, such as the plugin configuration values.


.SS CONFIG OPTIONS
The
.B config
command is used to make changes to the
.B /etc/rhsm/rhsm.conf
configuration file used by Subscription Manager. Almost all of the connection information used by Subscription Manager to access the subscription management service, content server, and any proxies is set in the configuration file. It also contains general configuration parameters like the frequency that Subscription Manager checks for subscriptions updates. The
.B rhsm.conf
file is organized into sections. For example, the
.B [server]
section is used to configure the subscription management service.
.PP
When changing a configuration, the settings are identified with the format
.I <section>.<parameter>
followed by a configuration value.

.TP
.B --list
Prints the current configurations for Subscription Manager.

.TP
.B --<section>.<parameter>=VALUE
Sets a new configuration value for the section parameter. For example:
.PP
.RS
.nf
--logging.default_log_level=DEBUG
.fi
.RE

.TP
.B --remove=<section>.<parameter>
Deletes the current configuration value for the section parameter without specifying a new value. Once deleted, Subscription Manager will use the default value for that parameter. If there are no defaults, then the configuration is ignored.

.PP
Review the man page for rhsm.conf (man rhsm.conf) for more detailed information on all of the configuration parameters.


.SS VERSION OPTIONS
The
.B version
command displays information about the current Subscription Manager package, the subscription service the system is registered to (if it is currently registered), and the subscription management server that the system is configured to use. For example:

.RS
.nf
[root@rhel-10 ~]# subscription-manager version
server type: Red Hat Subscription Management
subscription management server: 4.7.5-1
subscription management rules: 5.44
subscription-manager: 1.30.3-1.el10
.fi
.RE
.PP
This command has no unique options.


.SS COMMON OPTIONS
The following options are common to most of the commands and subcommands described above.
.TP
.B -h, --help
Prints the specific help information for the given command.

.TP
.B --proxy=PROXY
Uses an HTTP proxy. The
.I PROXY
name has the format
.I hostname:port.

.TP
.B --proxyuser=PROXYUSERNAME
Gives the username to use to authenticate to the HTTP proxy.

.TP
.B --proxypassword=PROXYPASSWORD
Gives the password to use to authenticate to the HTTP proxy.

.TP
.B --noproxy=NOPROXY
Specifies a list of domain suffixes which should bypass the HTTP proxy.

.TP
.B --no-progress-messages
Disables progress messages that are being displayed when waiting for a server response.

.SS REQUIRED OPTIONS
Some of the commands described above require standard authentication and environment options, such as \fB--username\fP, \fB--password\fP, \fB--org\fP, or \fB--environments\fP. In non-interactive sessions, these parameters must be passed directly as command-line arguments.
.PP
.B Note:
If required options are missing,
.B subscription-manager
will prompt for input. In a non-interactive shell or automated script, this prompt will cause execution to hang indefinitely. Always provide all necessary arguments when scripting subscription-manager to prevent blocking your automated scripts.


.SH DEPRECATED COMMANDS
Currently there are no deprecated commands.


.SH USAGE
The
.B subscription-manager
client tool has two major tasks:

.IP "1." 3
Handling the registration for a given system to a subscription management service
.IP "2." 3
Managing the entitlements granted by the subscription management service

.SS REGISTERING AND UNREGISTERING MACHINES
A system is either
.I registered
to a subscription management service -- which makes all of the subscriptions available to the system -- or it is not registered. Unregistered systems necessarily lack valid software subscriptions because there is no way to record that the subscriptions have been used nor any way to renew them.

.PP
The default subscription management service in the Subscription Manager configuration is the Customer Portal Subscription Management service. The configuration file can be edited before the system is registered to point to an on-premise subscription management service like Satellite.

.PP
Systems are usually registered to a subscription management service as part of their initial configuration, such as the kickstart process. However, systems can be registered manually after they are configured, can be removed from a content service, or re-registered.

.PP
If a system has never been registered (not even during first boot), then the
.B register
command will register the system with whatever subscription management service is configured in the
.B /etc/rhsm/rhsm.conf
file. This command requires, at a minimum, the username and password for an account to connect to the subscription management service. If the credentials aren't passed with the command, then
.B subscription-manager
prompts for the username and password interactively.

.PP
When there is a single organization or when using the Customer Portal Subscription Management service, only the username/password are required to register. For example:

.RS
.nf
subscription-manager register --username=admin --password=secret
.fi
.RE

.PP
With on-premise subscription services, such as Satellite, the infrastructure is more complex. The local administrator can define independent groups called
.I organizations
which represent physical or organizational divisions (\fB--org\fP). Those organizations can be subdivided into \fIenvironments\fP (\fB--environments\fP).
Optionally, the information about what subscription service (\fB--serverurl\fP) and content delivery network (\fB--baseurl\fP) to use for the system registration can also be passed (which overrides the Red Hat Subscription Manager configurations). The server and content URLs are usually configured in the Subscription Manager configuration by installing the katello-ca-consumer RPM before registering a system.

.RS
.nf
subscription-manager register --username=admin --password=secret
--org="IT Org" --environment="Library/IT" --serverurl=local-satellite.example.com --baseurl=https://local-satellite.example.com/pulp/content
.fi
.RE

.PP
If a system is in a multi-tenant environment and the organization is
.I not
provided with the registration request, registration fails with a remote server error. In the
.B rhsm.log,
there will be errors about being unable to load the owners interface.

.PP
If a system is registered and then somehow its subscription information is lost -- a drive crashes or the certificates are deleted or corrupted -- the system can be re-registered, with all of its subscriptions restored, by registering with the existing ID.

.RS
.nf
subscription-manager register --username=admin
--password=secret --consumerid=1234abcd
.fi
.RE

.PP
A system uses an SSL client certificate (its identity certificate) to authenticate to the subscriptions system to check for updates or changes to subscriptions. If the identity certificate is lost or corrupted, it can be regenerated using the
.B identity
command.

.RS
.nf
subscription-manager identity --regenerate
.fi
.RE

.PP
Appending the
.B --force
option will prompt for a username and password since these options are required when force is specified.

.RS
.nf
subscription-manager identity --regenerate --force
Username: jsmith
Password:
Identity certificate has been regenerated.
.fi
.RE

.PP
When a system is ready to be shut down for an extended time or transferred to another organization, running the
.B unregister
command removes the system from the subscription management service and returns its subscriptions back to the organization for reassignment to another system.

.RS
.nf
subscription-manager unregister
.fi
.RE

.SS LISTING PRODUCTS
The
.B list
command can be used to show what products are currently installed on the system. Appending
.B --matches=SEARCH
allows you to filter the list by name.
.PP
.RS
.nf
subscription-manager list --installed --matches="*Beta"

+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+

Product Name:	Red Hat Enterprise Linux for x86_64 Beta
Product ID:	486
Version: 		10.0 Beta
Arch:		x86_64
.fi
.RE

.SS CHANGING SUBSCRIPTION MANAGER CONFIGURATIONS
Subscription Manager uses the
.B /etc/rhsm/rhsm.conf
file for configuration, including what content and subscription management services to use. This configuration file can be edited directly, or it can be edited using the
.B config
command. Parameters and values are passed as arguments with the
.B config
command in the format
.I --<section>.<parameter>=value
, where
.I <section>
is the configuration section in the file: server, rhsm, rhsmcertd or logging.

.PP
For example, to turn off the reporting of the system's package profile to the subscription management service:

.RS
.nf
subscription-manager config --rhsm.report_package_profile=0
.fi
.RE

.PP
The entries in the
.B logging
section are somewhat special.
The keys in this section are a name of a logger.
The values are the logging level.
.PP
Valid levels are one of:
.B DEBUG
,
.B INFO
,
.B WARNING
,
.B ERROR
, or
.B CRITICAL
.
.PP
Valid logger names are the full module path of any Subscription Manager module.
For example:
.B subscription_manager
or
subscription_manager.managercli

.PP
There are three main top-level loggers: subscription_manager, rhsm, and rhsm-app.
All logger names begin with one of the above.

.PP
To set the default log level for all loggers (that are not otherwise set in the logging section), edit the
.B default_log_level
key in /etc/rhsm/rhsm.conf


.SS UPDATING FACTS
The information about a system, such as its hardware and CPU, its operating system versions, and memory, are collected by Subscription Manager in a list of
.I facts.
Subscription Manager uses these facts to determine what purchased subscriptions are compatible with the system. Whenever these facts change (such as installing an additional CPU), the facts can be updated immediately using the
.B facts
command.

.RS
.nf
subscription-manager facts --update
.fi
.RE

The collected facts can also be overridden by creating JSON files (named with a
.B .facts
extension) in the
.B /etc/rhsm/facts/
directory. The contents of these facts files must have a simple JSON format defined by a fact and value:

.RS
.nf
{"fact1":"value1", "fact2":"value2"}
.fi
.RE

.PP
After these fact files are created, running the
.B facts --update
command will upload a new copy of the system facts including the newly added or overridden facts to the subscription management service.

.SS KICKSTARTS
The
.B subscription-manager
tool can be run as a post-install script during the kickstart installation process. This allows subscription management registration to be automated with system installs. For example:

.RS
.nf
%post --log=/root/ks-post.log
/usr/sbin/subscription-manager register --org="IT Dept" --activationkey=it_key --force
.fi
.RE

.SH PROXY CONFIGURATION
.B subscription-manager
can be configured to use a proxy in several ways:
.IP \(bu 2
via standard
.B HTTP_PROXY
,
.B HTTPS_PROXY
,
.B NO_PROXY
environment variables (environment-level settings)
.IP \(bu 2
via options in
.B /etc/rhsm/rhsm.conf
(application-level settings)
.IP \(bu 2
via command-line arguments (command-level overrides)

.PP
Although
.B subscription-manager
respects environment variables for proxy configuration, this should still be avoided in favor of the configuration file (/etc/rhsm/rhsm.conf) for consistency and ease of maintenance across all tools and daemons.

Each option of the proxy configuration (hostname, port, host/domain pattern blocklist, username, password) is read independently, with precedence being command-line over configuration over environment, and then the resulting set of options is used to configure the proxy configuration.

For example,
if the
.B HTTP_PROXY
environment variable is set and
.B no_proxy
is set in
.B /etc/rhsm/rhsm.conf
then both are present in the effective proxy configuration.

If two equivalent options are set in different places, then the precedence determines which value is effective.

For example,
the
.B NO_PROXY
environment variable is set and the
.B no_proxy
configuration file option is set, then the value from the configuration file is the effective value.

.SH LOG FILES
The default log location for
.B subscription-manager
is 
.B /var/log/rhsm/rhsm.log.
When the program is run under non-root user (e.g. as dnf plugin) the logs are written to
.B $XDG_CACHE_HOME/rhsm/rhsm.log.

If the directory isn't writable, the logs are printed to stderr.

.SH IMPORTANT FILES
.IP \(bu 2
/etc/pki/consumer/*.pem
.IP \(bu 2
/etc/pki/entitlement/<serial>.pem
.IP \(bu 2
/etc/pki/product/*.pem
.IP \(bu 2
/etc/rhsm/rhsm.conf
.IP \(bu 2
/etc/rhsm/facts/*.facts
.IP \(bu 2
/var/log/rhsm/rhsm.log

.SH HISTORICAL NOTES
The
.B subscription-manager
client tool is available on Red Hat Enterprise Linux platform version 5.7 (and newer) and version 6.1 (and newer). Older versions of RHEL should register to Red Hat Network Classic using the
.B rhn_register
client tool.
.PP
Starting in RHEL version 10, the
.B subscription-manager
client tool has been greatly simplified by eliminating the need to explicitly attach subscriptions to systems. Now obsolete, the former
.B attach
command was a primary module used in to individually assign subscription entitlements to individually registered systems. This system level procedure was required prior to an organizational election to adopt Simple Content Access. By default, Red Hat subscription services now configure all organizations to grant entitlements in a Simple Content Access mode. Monitoring the quantity of subscription consumption for procurement purposes can now be handled at an organization level by subscription utilization reporting services. Learn more about this significant simplification in Subscription Management at https://\:access.redhat.com/\:articles/\:simple-content-access

.SH EARLY AUTHORS
Deon Lackey, <dlackey@redhat.com>, and Pradeep Kilambi, <pkilambi@redhat.com>

.SH CURRENT AUTHORS
CSI Client Tools Team, <csi-client-tools-bugs@redhat.com>

.SH SEE ALSO
\fBrhsm.conf\fR(5), \fBrhsm\-debug\fR(8), \fBrhsmcertd\fR(8) \fBrct\fR(8)

.SH BUGS
This tool is part of Red Hat Subscription Manager. To report bugs against this command-line tool, login and create an issue at https://\:redhat.atlassian.net/\:jira/\:software/\:c/\:projects/\:RHEL/\:issues?jql=component%3Dsubscription%2Dmanager
