.TH subscription-manager 8 "April 12, 2012" "version 2.1" "Subscription Management"  Deon Lackey 
.SH NAME
subscription-manager \- Register machines and manage subscriptions to products.

.SH SYNOPSIS
subscription-manager
.I command [options]

.SH DESCRIPTION
.B subscription-manager 
is a client program that registers a system with the Certificate-Based Red Hat Network. To register your system with RHN Classic or with an RHN Satellite 5.x system, then use the 
.B rhn_register
tool.

.PP
Red Hat provides content updates and support by issuing 
.I subscriptions
for its products. These subscriptions are allocated to systems (machines); once a system is subscribed to content, it is 
.I entitled
to install and update that software product. IT administrators need to track these subscriptions and how they are assigned. This entitlement and subscription management is a feature available for Red Hat platforms version 5.7 (and later) and version 6.1 (and later). 

.PP
For RHEL systems, content is delivered through the Red Hat Customer Portal. Subscriptions and systems are managed globally through the Red Hat entitlement service, which is integrated with the Customer Portal. Subscriptions are managed for the local system by using the Red Hat Subscription Manager tool. Subscription Manager is a local client which connects a system with the entitlement service. 

.PP
.B subscription-manager 
is the command-line based client for the Red Hat Subscription Manager tool.

.PP
The Subscription Manager performs several key operations:
.IP
* It registers machines to the Red Hat entitlement service and adds the machine to the systems inventory. Once a machine is registered, it can receive updates based on its subscriptions to any kind of software products.
.IP
* It lists both available and used (consumed) subscriptions.
.IP
* It allows administrators to both subscribe and unsubscribe a system from specific subscriptions. 
.PP
Subscription Manager can be used to autosubscribe a system, as well. The 
.B subscription-manager
command can even be invoked as part of a kickstart process.

.PP
Available subscriptions are based on the specific information about the machine's architecture. An entitlement is only considered 
.I available 
if the platform and hardware can support that specific product.

.PP
Subscription Manager also collects and 
summarizes system facts related to its hardware, operating system, and other characteristics. These facts can be edited in the Subscription Manager configuration and displayed through Subscription Manager.

.PP
There is also a Subscription Manager GUI, which can be invoked simply by running 
.B subscription-manager-gui 
from the command line.

.PP
Entitlement and subscription management is only available for RHEL 5.7/6.1 and later systems. Older systems should register to Red Hat Network Classic using the 
.B rhn_register
command.

.SH COMMANDS AND OPTIONS
.B subscription-manager 
has specific options available for each command, depending on what operation is being performed. The Subscription Manager commands are related to the different subscription operations:

.IP
1. register

.IP
2. unregister

.IP
3. subscribe

.IP
4. unsubscribe

.IP
5. release

.IP
6. service-level

.IP
7. import 

.IP
8. redeem

.IP
9. list

.IP
10. refresh

.IP
11. environments

.IP
12. repos

.IP
13. orgs

.IP
14. identity

.IP
15. facts

.IP
16. clean

.IP
17. config


.SS COMMON OPTIONS
.TP
.B -h, --help
Prints the specific help information for the given command.

.TP
.B --proxy=PROXY
Uses an HTTP proxy. The 
.I PROXY
name has the format 
.I hostname:port.


.TP
.B --proxyuser=PROXYUSERNAME
Gives the username to use to authenticate to the HTTP proxy.

.TP
.B --proxypass=PROXYPASSWORD
Gives the password to use to authenticate to the HTTP proxy.

.SS REGISTER OPTIONS
The 
.B register 
command registers a new machine to the entitlement service.

.TP
.B --username=USERNAME
Gives the username for the account which is registering the system; this user account is usually tied to the user account for the content delivery system which supplies the content. Optional, for user-based authentication.

.TP
.B --password=PASSWORD
Gives the user account password. This is required.

.TP
.B --type=CONSUMERTYPE
Sets the type of consumer to register. Most systems will use the default value of 
.B system.
For development or test systems, this can be 	 
.B person
, which indicates a personal (rather than organizational) entitlement subscription. Other systems can be
.B candlepin
for a local content service or 
.B domain
for an IP domain.

.TP
.B --name=CONSUMERNAME
Sets the name of the consumer (machine) to register. This defaults to be the same as the hostname.


.TP
.B --consumerid=CONSUMERID
References an existing consumer ID to reregister a system. The consumer ID is used as an inventory number for the system in the entitlements service database. If the entitlements data are lost or corrupted, reregistering the system restores it.

.TP
.B --activationkey=KEYS
Gives a comma-separated list of product keys to use to redeem or apply specific subscriptions to the machine. This is used generally for preconfigured machines, which may already have products installed and subscriptions allocated for that consumer.
.IP
When the 
.B --activationkey
option is used, it is not necessary to use the 
.B --username 
and 
.B --password
options, because the authentication information is implicit in the activation key.
.IP
In hosted or single organization environments, it is not necessary to specify an organization with the 
.B --org
option, but in multi-organization environments, this is required.
.IP
For example:
.RS
.nf
subscription-manager register --org="IT Dept" --activationkey=1234abcd
.fi
.RE

.IP
Giving the org name is not necessary in hosted environments or infrastructures which have only a single organization.


.TP
.B --autosubscribe
Automatically subscribes this system to the best-matched compatible subscription.


.TP
.B --servicelevel=LEVEL
Sets the preferred service level to use with subscriptions added to the system. Service levels are commonly premium, standard, and none, though other levels may be available depending on the product and the contract. This preference can only be used in conjunction with the 
.B --autosubscribe
option, and then it is used as one of the factors for matching subscriptions.

.TP
.B --force
Registers the system even if it is already registered. Normally, any register operations will fail if the machine is already registered. With 
.B --force, 
the existing consumer entry is unregistered first, all of its subscriptions are returned to the pool, and then the consumer is registered as a new consumer.

.TP
.B --org=ORG
Assigns the consumer to an organization. Infrastructures which are managed on-site may be 
.I multi-tenant,
meaning that there are multiple organizations within one customer unit. A consumer may be assigned manually to one of these suborganizations. If there is only one organization configured (which is the case with infrastructures using the hosted service), then this is not used. With multi-tenant environments, this is required.

.TP
.B --environment=ENV
Registers the consumer to an environment within an organization.


.SS UNREGISTER OPTIONS
The 
.B unregister 
command unregisters a machine, which strips its subscriptions and removes the machine from the entitlement service.

.PP
This command has no options.

.SS SUBSCRIBE OPTIONS
The 
.B subscribe
command allocates a specific subscription to the machine. 

.TP
.B --pool=POOLID
Gives the ID for the entitlements pool (collection of products) to subscribe the machine to. This option is required, unless 
.B --auto
is used.

.TP
.B --quantity=NUMBER
Subscribes the system to a specified number of subscriptions. Subscriptions may have certain limits on them, like the number of sockets on the machine or the number of allowed virtual guests. It is possible to assign multiple subscriptions (or 
.I stacking
subscriptions) to cover the number of sockets, guests, or other characteristics.

.TP
.B --auto
Automatically subscribes this system to the best-matched compatible subscription or subscriptions.

.TP
.B --servicelevel=LEVEL
Sets the preferred service level to use with subscriptions added to the system. Service levels are commonly premium, standard, and none, though other levels may be available depending on the product and the contract. This preference can only be used in conjunction with the 
.B --auto
option, and then it is used as one of the factors for matching subscriptions.

.SS UNSUBSCRIBE OPTIONS
The 
.B unsubscribe
command removes a subscription allocation from the machine. (This does not uninstall the associated products.)

.TP
.B --serial=SERIALNUMBER
Gives the serial number of the entitlement certificate for the specific product that is being unsubscribed. Entitlement certificates for subscribed products are in a certificate, in 
.B /etc/pki/entitlement/<serial_number>.pem.

.TP
.B --all
Unsubscribes the system from 
.I all 
of the products it's subscribed to.


.SS RELEASE OPTIONS
The 
.B release
command sets a sticky OS version to use when installing or updating packages. This sets a preference for the minor version of the OS, such as 6.2 or 6.3. This can prevent unplanned or unsupported operating system version upgrades when an IT environment must maintain a certified configuration.

.TP
.B --list
Lists the available OS versions.

.TP
.B --set=RELEASE
Sets the minor (Y-stream) release version to use, such as 6.3.


.SS SERVICE-LEVEL OPTIONS
The 
.B service-level
command displays the current configured service level 
.I preference 
for products installed on the system. For example, if the service level preference is standard, then a subscription with a standard service level is selected when autosubscribing the system. 

.IP
The 
.B service-level
command does not set the service level for the system; it only shows its current setting or available settings. The service level preference must be set in the Subscription Manager UI.

.TP
.B --list
Lists the available service levels.

.TP
.B --show
Shows the system's current service-level preference.


.SS IMPORT OPTIONS
The 
.B import
command imports and applies an entitlement certificate for the consumer which was generated externally, such as in the Customer Portal, and then copied over to the machine. Importing can be necessary if a machine is pre-configured in the subscription service or if it is offline or unable to access the subscription service but it must be properly subscribed to relevant entitlements.

.TP
.B --certificate=CERTIFICATE_FILE
Points to a certificate PEM file which contains the entitlement certificate. This can be used multiple times to import multiple entitlement certificates.

.SS REDEEM OPTIONS
The 
.B redeem 
command is used for machines that are purchased from third-party vendors that include a subscription. The redemption process essentially autosubscribes the machine to the pre-selected subscription that the vendor supplied. 

.TP
.B --email=EMAIL
Gives the email account to send the redemption notification message to.

.TP
.B --locale=LOCALE
Sets the locale to use for the message. If none is given, then it defaults to the local system's locale.

.TP
.B --org=ORG
Identifies the organization which issued the entitlement being redeemed.


.SS LIST OPTIONS
The 
.B list
command lists all of the subscriptions that are compatible with a machine. The options allow the list to be filtered by subscriptions that are used by the machine or unused subscriptions that are available to the machine.

.TP
.B --available
Lists available subscriptions which the machine has not subscribed to.

.TP
.B --consumed
Lists all of the subscriptions that the machine is currently subscribed to.

.TP
.B --ondate=YYYY-MM-DD
Sets the date to use to search for active and available subscriptions. The default (if not explicitly passed) is today's date; using a later date looks for subscriptions which will be active then. This is only used with the 
.B --available
option.

.TP
.B --installed
Lists products which are currently installed on the system which may (or may not) have subscriptions associated with them, as well as subscribed products which may (or may not) be installed.

.TP
.B --all
Lists all possible subscriptions that have been purchased by the organization, even if they don't match the architecture of the system. This is used with the
.B --available 
option. 


.TP
.B --servicelevel
Displays the current preferred service level for the system. Service levels commonly are none, standard, or premium. If no service-level preference is set, then the display value is blank. For example:
.nf
subscription-manager list --servicelevel
Current service level: 
.fi


.SS REFRESH OPTIONS
The 
.B refresh
command pulls the latest entitlement data from the server. Normally, the system polls the entitlement server at a set interval (4 hours by default) to check for any changes in the available subscriptions. The 
.B refresh
command checks with the entitlement server right then, outside the normal interval.

.PP
This command has no options.


.SS ENVIRONMENTS OPTIONS
The 
.B environments
command lists all of the environments that have been configured for an organization. This command is only used for organizations which have a locally-hosted subscriptions or content service of some kind, like Subscription Asset Manager. The concept of environments -- and therefore this command -- have no meaning in a hosted subscription/content structure.

.TP
.B --username=USERNAME
Gives the username for the account to use to connect to the organization account.

.TP
.B --password=PASSWORD
Gives the user account password. This is required.

.TP
.B --org=ORG
Identifies the organization for which to list the configured environments.


.SS REPOS OPTIONS
The 
.B repos
command lists all of the repositories that are available to a consumer. This command is only used for organizations which have a locally-hosted content service of some kind, like Subscription Asset Manager. With Red Hat's hosted content service, there is only one central repository.

.TP
.B --list
Lists all of the repositories that are provided by the content service used by the consumer.


.SS ORGS OPTIONS
The 
.B orgs
command lists all of the organizations which are available to the specified user accounts. A multi-tenant infrastructure may have multiple organizations within a single customer, and users may be restricted to access only a subset of the total number of organizations.

.TP
.B --username=USERNAME
Gives the username for the account to use to connect to the organization account.

.TP
.B --password=PASSWORD
Gives the user account password. This is required.


.SS IDENTITY OPTIONS
The 
.B identity 
command handles the UUID of a system, which identifies the system to the entitlement service after registration. This command can simply return the UUID or it can be used to restore the registration of a previously-registered system to the entitlement service.

.TP
.B --regenerate
Requests that the entitlement service issue a new identity certificate for the system, using an existing UUID in the original identity certificate. If this is used alone, then the
.B identity 
command also uses the original identity certificate to bind to the entitlement server, using certificate-based authentication.

.TP
.B --username=USERNAME
Gives the username for the account which is registering the system; this user account is usually tied to the user account for the content delivery system which supplies the content. Optional, for user-based authentication.

.TP
.B --password=PASSWORD
Gives the user account password. Optional, for user-based authentication.

.TP
.B --force
Regenerates the identity certificate for the system using username/password authentication. This is used with the 
.B --regenerate
option. 
.B --regenerate
alone will use an existing identity certificate to authenticate to the entitlement service. If the certificate is missing or corrupted or in other circumstances, then it may be better to use user authentication rather than certificate-based authentication. In that case, the 
.B --force
option requires the username or password to be given either as an argument or in response to a prompt.


.SS FACTS OPTIONS
The
.B facts 
command lists the system information, like the release version, number of CPUs, and other architecture information.

.TP
.B --list
Lists the system information. These are simple 
.I attribute: value
pairs that reflect much of the information in the 
.B /etc/sysconfig
directory
.nf
cpu.architecture: x86_64
cpu.core(s)_per_socket: 1
cpu.cpu(s): 2
cpu.cpu_family: 6
cpu.cpu_mhz: 1861.776
cpu.cpu_op-mode(s): 64-bit
cpu.cpu_socket(s): 2
cpu.hypervisor_vendor: KVM
cpu.model: 2
cpu.numa_node(s): 1
cpu.numa_node0_cpu(s): 0,1
cpu.stepping: 3
cpu.thread(s)_per_core: 1
cpu.vendor_id: GenuineIntel
cpu.virtualization_type: full
distribution.id: Santiago
distribution.name: Red Hat Enterprise Linux Workstation
distribution.version: 6.1
----

.fi

.TP
.B --update
Updates the system information. This is particularly important whenever there is a hardware change (such as adding a CPU) or a system upgrade because these changes can affect the subscriptions that are compatible with the system.

.SS CLEAN OPTIONS
The 
.B clean
command removes all of the subscription and identity data from the local system 
.I without affecting the consumer information in the entitlement service. 
This means that any of the subscriptions consumed by the system are still consumed and are not available for other systems to use. The 
.B clean
command is useful in cases where the local entitlement information is corrupted or lost somehow, and the system will be reregistered using the 
.B register --consumerid=EXISTING_ID
command.

.PP
This command has no options.

.SS CONFIG OPTIONS
The 
.B config
command changes the 
.B rhsm.conf
configuration file used by Subscription Manager. Almost all of the connection information used by Subscription Manager to access the subscription server, content server, and any proxies is set in the configuration file, as well as general configuration parameters like the frequency Subscription Manager checks for entitlements updates. There are major divisions in the 
.B rhsm.conf
file, such as 
.B [server]
which is used to configure the subscription server. When changing the Subscription Manager configuration, the settings are identified with the format 
.I section.name
and then the new value. For example:
.nf
server.hostname=newsubscription.example.com
.fi

.TP
.B --list
Prints the current configuration for Subscription Manager.

.TP
.B --remove=section.name
Deletes the current value for the parameter without supplying a new parameter. A blank value tells Subscription Manager to use service default values for that parameter. If there are no defaults, then the feature is ignored.

.TP
.B --section.name=VALUE
Sets a parameter to a new, specified value. This is commonly used for connection settings:
.IP
* server.hostname (subscription server)
.IP
* server.proxy
.IP
* server.proxy_port
.IP
* server.proxy_user
.IP
* server.proxy_password
.IP
* rhsm.baseurl (content server)
.IP
* rhsm.certFrequency


.SH USAGE
.B subscription-manager 
has two major tasks:

.IP
1. Handling the registration for a given system to an entitlement service

.IP
2. Handling the product subscriptions for a machine.

.PP
.B subscription-manager 
makes it easier for network administrators to maintain parity between software subscriptions and updates and their installed products by tracking and managing what machines are subscribed to and when those subscriptions expire or are exceeded.



.SS REGISTERING AND UNREGISTERING MACHINES
A machine is either 
.I registered 
to an entitlement and content service -- which makes all of the subscriptions available to the machine -- or it is not registered. Unregistered machines necessarily lack valid software entitlements because there is no way to record that the subscriptions have been used or to renew them.

.PP
Machines are usually registered to an entitlement service as part of their initial configuration, such as the firstboot or kickstart process. However, machines can be registered manually after they are configured, can be removed from a content service, or reregistered.

.PP
If a machine has never been registered (not even during firstboot), then the 
.B register
command will register the machine with whatever entitlement service is configured in the 
.B /etc/rhsm/rhsm.conf
file. This command requires, at a minimum, the username and password for an account to connect to the entitlement service. If the credentials aren't passed with the command, then 
.B subscription-manager
prompts for the username and password interactively.

.PP
For an environment with a single organization -- such as a hosted system -- all that is required is the username/password set. For example:

.nf
subscription-manager register --username=admin --password=secret
.fi

.PP
For a multi-tenant environment, then it is also necessary to specify the organization to which to register the system. For example:

.nf
subscription-manager register --username=admin --password=secret
--org="IT Dept"
.fi

.PP
Some information is assigned automatically. Subscription Manager automatically generates a unique consumer ID for the system which is used by the entitlement service and it assigns a consumer type, which indicates what kinds of software are available for the machine. The name for the consumer entry can be manually assigned (for use within a local inventory system, for instance). A handful of subscriptions (such as specialized servers for content or identity management) have their own specific consumer type. For example:

.nf
subscription-manager register --username=admin 
--password=secret --type=system --name=server1
--org="IT Dept"
.fi

.PP 
If a system is in a multi-tenant environment and the organization is 
.I not
provided with the registration request, registration fails with a remote server error. In the
.B rhsm.log,
there will be errors about being unable to load the owners interface.

.PP
If a system is registered and then somehow its entitlement information is lost -- a drive crashes or the certificates are deleted or corrupted -- the system can be reregistered, with all of its subscriptions restored, by registering with the existing consumer ID.

.nf
subscription-manager register --username=admin 
--password=secret --consumerid=1234abcd
.fi

.PP
A consumer uses an SSL client certificate (its identity certificate) to authenticate to the entitlements system to check for updates or changes to subscriptions. If the identity certificate is lost or corrupted, it can be regenerated using the 
.B identity
command.
.RS
.nf
subscription-manager identity --regenerate
.fi
.RE

.PP
Using the 
.B --force
option will prompt for the username and password for the account, if one isn't given, and then return the new consumer ID and the hostname of the registered system.

.nf
subscription-manager identity --force
Username: jsmith
Password: 
eff9a4c9-3579-49e5-a52f-83f2db29ab52 server.example.com
.fi


.PP
A machine is unregistered and removed as a consumer from the entitlements service simply by running the 
.B unregister
command. Unregistering and unsubscribing a service can free up entitlement subscriptions when a machine is taken offline or moved to a different department. 
.RS
.nf
subscription-manager unregister
.fi
.RE

.PP
An option with registration, 
.B --autosubscribe
, will automatically subscribe the newly-registered system to the entitlements pool which best matches the system architecture and configuration. This option allows the system to be subscribed as part of the registration process, rather than separately managing subscriptions.
.RS
.nf
subscription-manager register --username=admin --password=secret 
--autosubscribe
.fi
.RE

.PP
Autosubscribe also supports an option to set a preferred service level with the selected subscriptions, the 
.B --servicelevel
option. In this case, the 
.B --servicelevel
option sets a preference that helps the autosubscribe process select appropriate subscriptions. For example, if the preferred service level for a production server is premium, and there are three matching subscriptions with different service levels (none, standard, and premium), the autosubscribe process selects the subscription which offers a premium service level.

.RS
.nf
subscription-manager register --username=admin --password=secret 
--autosubscribe --servicelevel=premium
.fi
.RE

.SS LISTING, SUBSCRIBING, AND UNSUBSCRIBING TO PRODUCTS
A 
.I subscription
is essentially the right to install, use, and receive updates for a Red Hat product. (Sometimes multiple individual software products are bundled together into a single subscription.) When a machine is registered, the entitlements and content service is aware of the machine and has a list of all of the possible product subscriptions that the machine can install and use. A machine is allocated a product subscription by 
.I subscribing
to the entitlement pool that makes that product available. A machine releases that entitlement (meaning, it unassigns that product so that another machine can use that entitlement count) by 
.I unsubscribing.

.PP The 
.B list
command shows you what subscriptions are available specifically to the system (meaning subscriptions which are active, have available quantities, and match the hardware and architecture) or all  subscriptions for the organization. Using the 
.B --ondate
option shows subscriptions that are or will be active at a specific time (otherwise, it shows subscriptions which are active today).

.RS
.nf
subscription-manager list --available --ondate=2012-01-31
+-------------------------------------------+
    Available Subscriptions
+-------------------------------------------+


ProductName:        Awesome OS Server
ProductId:          AOS001
PoolId:             8a90f88e2e3802ab012e380345de0203
Quantity:           5                        
Expires:            2012-02-17
.fi
.RE

.PP
The 
.B list
command can also be used to show what products you currently have installed, as a way of tracking what products you have versus what subscriptions you have on the machine.
.RS
.nf
subscription-manager list --installed

+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+

ProductName:         Red Hat Enterprise Linux Entitlement
Status:              Not Subscribed           
Expires:                                      
Subscription:                                 
ContractNumber:                               
AccountNumber:                                


ProductName:         Awesome OS Server 
Status:              Not Installed            
Expires:             2012-02-20               
Subscription:        54129829316535230        
ContractNumber:      39                       
AccountNumber:       12331131231
.fi
.RE

.PP
Subscribing a machine requires the ID for the entitlement pool (the 
.I --pool
option). For example:
.RS
.nf
subscription-manager subscribe 
--pool=ff8080812bc382e3012bc3845da100d2
.fi
.RE

.pp
As with the 
.B register
command, the system can be autosubscribed to the best-fitting subscriptions using the 
.B --auto
option:
.RS
.nf
subscription-manager subscribe --auto
.fi
.RE


.PP
Autosubscribe also supports an option to set a preferred service level with the selected subscriptions, the 
.B --servicelevel
option. In this case, the 
.B --servicelevel
option sets a preference that helps the autosubscribe process select appropriate subscriptions. For example, if the preferred service level for a production server is premium, and there are three matching subscriptions with different service levels (none, standard, and premium), the autosubscribe process selects the subscription which offers a premium subscription.

.RS
.nf
subscription-manager subscribe --auto --servicelevel=premium
.fi
.RE

.PP
Some subscriptions define a count on the consumer, like the number of sockets on the machine or the number of virtual guests on a host. You can 
.I stack
multiple subscriptions together to cover the count. For example, if there is a four socket server, you can use two subscriptions for "RHEL Server for Two Sockets" to cover the socket count. To specify the number of subscriptions to use, 
use the 
.B --quantity
option. For example:
.RS
.nf
subscription-manager subscribe 
--pool=ff8080812bc382e3012bc3845da100d2
--quantity=2
.fi
.RE

.PP
Unsubscribing a machine removes it from the product or entitlement pool, which releases that entitlement subscription it had consumed. The machine remains registered with the entitlement service. Each product has an identifying X.509 certificate installed with it. To unsubscribe from a subscription for a specific product, specify the serial number of the certificate:
.RS
.nf
subscription-manager unsubscribe --serial=1128750306742160
.fi
.RE

.PP
Giving the 
.B unsubscribe
command with the 
.B --all
option unsubscribes the machine from every subscription it has consumed.


.SS REDEEMING EXISTING SUBSCRIPTIONS
Sometimes, a machine may come pre-configured with products and subscriptions. Rather than subscribing to a pool and claiming a subscription, this system simply needs to 
.I redeem
its existing subscriptions. 

.PP
After registration, subscriptions on pre-configured machines can be claimed using the 
.B redeem
command, which essentially autosubscribes the system to its pre-existing subscriptions.
.RS
.nf
subscription-manager redeem --email=admin@example.com --org="IT Dept"
.fi
.RE

.SS VIEWING LOCAL SUBSCRIPTION & CONTENT PROVIDER INFORMATION
Red Hat has a hosted environment, through the Customer Portal, that provides centralized access to subscription management and content repositories. However, organizations can use other tools -- like Subscription Manager -- for content hosting  and subscription management. With a local content provider, the organization, environments, repositories, and other structural configuration is performed in the content provider. Red Hat Subscription Manager can be used to display this information, using the 
.B environments, orgs,
and
.B repos
commands.

.RS
.nf
subscription-manager repos --list

subscription-manager environments --username=jsmith
--password=secret --org=prod

subscription-manager orgs --username=jsmith
--password=secret 
.fi
.RE

.SS CHANGING SUBSCRIPTION MANAGER CONFIGURATION
The Subscription Manager CLI and UI both use the 
.B /etc/rhsm/rhsm.conf
file for its configuration, including what content and subscription services to use and management settings like autohealing. This configuration file can be edited directly, or it can be edited using the 
.B config 
command. Parameters and values are passed as arguments with the 
.B config
command in the format 
.I --section.parameter=value
, where 
.I section
is the configuration section in the file: server, rhsm, or rhsmcertd.

.PP
For example, to change the hostname of the subscription service host:
.RS
.nf
subscription-manager config --server.hostname=myserver.example.com
.fi
.RE


.SS UPDATING FACTS
The information about a system, such as its hardware and CPU, its operating system versions, and memory, are collected by Subscription Manager in a list of 
.I facts.
Subscription Manager uses these facts to determine what purchased entitlements are compatible with the system. Whenever these facts change (such as installing an additional CPU), the facts can be updated immediately using the 
.B facts
command.

.RS
.nf
subscription-manager facts --update
.fi
.RE

The collected facts can also be overridden by creating a JSON file in the 
.B /etc/rhsm/facts/
directory. These have simple formats that define a fact and value:
.RS
.nf
{"fact1": "value1","fact2": "value2"}
.fi
.RE

.PP
Any fact override file must have a 
.B .facts
extension.

.PP
When these fact files are added, running the 
.B facts
command will update the collected facts with the new, manual facts or values.

.SS ENTITLEMENTS AND KICKSTART
The 
.B subscription-manager
tool can be run as a post-install script as part of the kickstart installation process. This allows entitlement management (registration and subscription) to be automated along with installation. For example:
.RS
.nf
%post --log=/root/ks-post.log
/usr/sbin/subscription-manager register --username admin --password secret --org 'east colo' --autosubscribe --servicelevel=premium --force
.fi
.RE

.SS GETTING INFORMATION FROM CERTIFICATES
Both Subscription Manager and product information is contained in X.509 certificates. To obtain this information, use tools like 
.B openssl
or
.B pk12util
to pretty-print the certificate information. For example:
.nf
openssl x509 -text -in /etc/pki/consumer/cert.pem

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 9 (0x9)
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN=server.example.com, C=US, L=Mountain View
        Validity
            Not Before: Sep 21 19:01:01 2010 GMT
            Not After : Sep 21 19:01:01 2011 GMT
        Subject: CN=78cf3c59-24ec-4228-a039-1b554ea21319
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:cd:22:86:2b:77:1b:40:b2:be:8e:06:8e:b8:df:
.fi


.SH FILES
.IP
* /etc/pki/consumer/*.pem
.IP
* /etc/pki/entitlement/<serial>.pem
.IP
* /etc/pki/product/*.pem
.IP
* /etc/rhsm/rhsm.conf 
.IP
* /etc/rhsm/facts/*.facts

.SH AUTHORS
Deon Lackey, <dlackey@redhat.com>, and Pradeep Kilambi, <pkilambi@redhat.com>

