.TH subscription-manager-gui 8 "January 25, 2011" "version 1.0" "Subscription Manager GUI"  Deon Lackey 
.SH NAME
subscription-manager-gui \- Launches the UI client of the Subscription Manager.

.SH SYNOPSIS
subscription-manager-gui

.SH DESCRIPTION
.B subscription-manager-gui
opens the local client tool to manage subscriptions, entitlements, and installed products on Red Hat Enterprise Linux systems. The same tasks that can be performed by invoking 
.B subscription-manager
can be performed in the GUI, including registering systems with the Red Hat Entitlement Service, subscribing and unsubscribing to entitlements, and viewing the subscription status of installed products.

.PP
The Subscription Manager UI can also be opened by going through the 
.B System > Administration 
menu and selecting the 
.B Red Hat Subscription Manager
item.


.SH USAGE
This command has no options.


.SH ASSOCIATED FILES
.IP
* /usr/sbin/subscription-manager-gui
.IP
* /usr/sbin/subscription-manager
.IP
* /etc/rhsm/rhsm.conf 

.SH BUGS
This client is part of the subscription management system available in Red Hat Enterprise Linux. To file bugs related to this tool, go to https://bugzilla.redhat.com/ and select Red Hat > Red Hat Enterprise Linux # > subscription-manager.


.SH AUTHORS
Deon Lackey, <dlackey@redhat.com>.

.SH COPYRIGHT
Copyright (c) 2010, 2011 Red Hat, Inc. This is licensed under the GNU General Public License, version 2 (GPLv2). A copy of this license is available at http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
