.\" subscription-manager-cli - Subscription Manager Command-Line tool
.TH "subscription-manager-cli" "8" ""  "Pradeep Kilambi" ""
.SH "NAME"
subscription-manager-cli \- Subscription Manager Cli tool
.SH "SYNOPSIS"
\fBsubscription-manager-cli\fP [command] [options]
.SH "DESCRIPTION"
.PP 
\fBsubscription-manager-cli\fP is a command line utility to Register and Manage Red Hat Enterprise Linux Subscriptions. It allows users to register clients to Red Hat Entitlement Platform, list available and consumed subscription information, and subscribe to and unsubscribe from specific subscriptions.
.PP
.PP 
.SH "COMMANDS"
Unless the --help or -h option is given, one of the following commands
must be present\&.
.PP
.PP 
.IP "\fBregister\fP [options]"
Registers your client to a Red Hat Entitlement Platform. This will create an identity on this system for
use with all other commands\&.
.IP 
.IP "\fBlist\fP [options]"
List available, consumed or installed product/subscription information for a registered system\&.
If no options are specified, this command lists currently installed products and their
subscription status.
.IP 
.IP "\fBsubscribe\fP [options]"
Subscribe the registered client to a product, registration token or entitlement Pool ID. 
Specify your account subscription number as your registration token.
.IP
.IP "\fBunsubscribe\fP [options]"
Unsubscribes the registered product from specific or all subscriptions. If no option is specified
\fIall\fP consumed subscriptions will be relinquished and system will be unsubscribed. If you want to unsubscribe 
specific subscription(s), provide the serial number.
.IP 
.IP "\fBhelp\fP [command]"
Displays the help content for a given command or for all commands if left blank\&.
.IP
.PP
.SH "GENERAL OPTIONS"
.PP 
.IP "\fB\-h, \-\-help\fP"
Display a help message and exit\&.
.PP
.SH "REGISTRATION OPTIONS"
.PP
.IP "\fB\-u, \-\-username\fP" 
Specify your Red Hat user account information for registration\&.
.br
.IP "\fB\-p, \-\-password\fP" 
Specify your Red Hat user account password\&.
.br
.IP "\fB\-v, \-\-verbose\fP" 
Run with debugging output\&.
.br
.SH "LIST OPTIONS"
.PP
.br
If none of the following options are specified, this command lists currently installed products and their subscription state.
.br
.IP "\fB\ \-\-available\fP" 
Lists all available subscriptions for the registered account.
.br
.IP "\fB\ \-\-consumed\fP"
Lists any consumed product subscriptions for the registered account.
.br
.PP
.SH "SUBSCRIBE OPTIONS"
.PP
.IP "\fB\ \-\-product\fP" 
Specify products by their name (examples include RHEL AP, RHEL-Server-6, Virtualization, and more).
.IP "\fB\ \-\-regtoken\fP"
Specify the registration token number to subscribe this registered client.
.IP "\fB\ \-\-pool\fP"
Specify the entitlement Pool ID to subscribe this registered client.
.br
.PP
.SH "UNSUBSCRIBE OPTIONS"
.PP
.br
If none of the following options are specified, this command removes \fIall\fP subscriptions\&.
.br
.IP "\fB\ \-\-product\fP"
Specify products to unsubscribe from by their name (examples include RHEL AP, RHEL-Server-6, Virtualization, and more).
.PP
.SH "FILES"
.nf
/etc/rhsm/rhsm.conf
.fi 

.PP
.SH "AUTHORS"
.nf
.I Pradeep Kilambi <pkilambi@redhat.com>
.fi
