Document: subscription-manager
Title: Debian subscription-manager Manual
Author: <insert document author here>
Abstract: This manual describes what subscription-manager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/subscription-manager/subscription-manager.sgml.gz

Format: postscript
Files: /usr/share/doc/subscription-manager/subscription-manager.ps.gz

Format: text
Files: /usr/share/doc/subscription-manager/subscription-manager.text.gz

Format: HTML
Index: /usr/share/doc/subscription-manager/html/index.html
Files: /usr/share/doc/subscription-manager/html/*.html
