upstream_package_name: subscription-manager
downstream_package_name: subscription-manager
specfile_path: subscription-manager.spec
upstream_tag_template: "subscription-manager-{version}-1"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-10
      - fedora-all

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-10
      - fedora-all

#  - job: tests
#    trigger: pull_request
#    identifier: "unit/centos-stream"
#    targets:
#      - centos-stream-10
#    labels:
#      - unit
#    tf_extra_params:
#      environments:
#        - artifacts:
#            - type: repository-file
#              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/centos-stream-$releasever/group_yggdrasil-latest-centos-stream-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/fedora"
    targets:
      - fedora-all
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/fedora-$releasever/group_yggdrasil-latest-fedora-$releasever.repo
