upstream_package_name: subscription-manager
downstream_package_name: subscription-manager
specfile_path: subscription-manager.spec
upstream_tag_template: "subscription-manager-{version}-1"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-10
      - fedora-all

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-10
      - fedora-all
