#! /usr/bin/env python
#
# Copyright (c) 2016 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation.
#
import dbus
import sys
import optparse
import logging
import rhsmlib.dbus as common
import rhsmlib.dbus.facts.constants as constants
import rhsmlib.dbus.facts.root as root

from rhsmlib import import_class
from rhsmlib.dbus.server import Server

common.init_root_logger()


def main(args):
    bus_class = dbus.SystemBus
    bus_name = constants.FACTS_DBUS_INTERFACE

    if len(args) > 0:
        bus_class = import_class(args[0])

    if len(args) > 1:
        bus_name = args[1]

    object_classes = [
        root.FactsRoot,
    ]

    Server().run(
        bus_class=bus_class,
        bus_name=bus_name,
        object_classes=object_classes)
    return 0


if __name__ == "__main__":
    parser = optparse.OptionParser()
    parser.add_option("-v", "--verbose", action="store_true")
    (options, args) = parser.parse_args()

    if options.verbose:
        logger = logging.getLogger('')
        logger.setLevel(logging.DEBUG)

    sys.exit(main(args))
