#!/bin/bash

# For a given bus/service name, find all of it's object paths
# and show introspection data for each.
# Uses 'busctl' cli for the heavy work.
#
# If a service name isn't specified, default to all the
# well known names that have been acquired. This potentially
# doesn't include apps that only use a unique name, or services
# that need to be activated.
#
# Example usage:
# $ dbus-show org.storaged.Storaged

BUS=${BUS:-"system"}


if [ -n "${1}" ]
then
    SERVICENAMES=( "$@" )
else
    SERVICENAMES=( $(busctl --no-legend "--${BUS}" --acquired | awk -e '{print $1}') )
fi


echo "$@"
echo "${SERVICENAMES[@]}"
# for f in "${files[@]}"
for service_name in "${SERVICENAMES[@]}"
do

    dbus_paths=$(busctl "--${BUS}" tree  --list "${service_name}")
    tree_exit_code="$?"

    if [ "${tree_exit_code}" -eq "1" ]
    then
        echo "Service name ${service_name} not found on this bus."
        continue
    fi

    for dbus_path in ${dbus_paths}
    do
        echo "service name: ${service_name}"
        echo "object path: ${dbus_path}"
        intro_data=$(busctl "--${BUS}" introspect --no-legend "${service_name}" "${dbus_path}")

        if [ -n "${intro_data}" ]
        then
            echo "${intro_data}"
        fi

        echo
    done

    echo
done

