FROM fedora:34

MAINTAINER "Candlepin Team" <candlepin@redhat.com>

RUN dnf install --disablerepo=updates -y \
    gettext \
    git \
    jss \
    openssl \
    bind-utils \
    dbus-glib \
    dbus-glib-devel \
    gcc \
    git \
    postfix \
    python3-pip \
    sudo \
    vim \
    wget \
    zsh \
    cmake \
    dbus-daemon \
    desktop-file-utils \
    GConf2-devel \
    gtk3-devel \
    intltool \
    json-c-devel \
    libdnf-devel \
    libnotify-devel \
    make \
    openssl-devel \
    python27 \
    rarian-compat \
    rpmlint \
    xorg-x11-server-Xvfb \
    python3-devel \
    python3-decorator \
    python3-six \
    python3-dateutil \
    python3-iniparse \
    python3-nose \
    python3-coverage \
    python3-polib \
    python3-decorator \
    python3-inotify \
    python3-simplejson \
    python3-sphinx \
    python3-rpm \
    python3-gobject-base \
    python3-ethtool \
    redhat-rpm-config \
    && dnf clean all

RUN mkdir /build
COPY requirements.txt dev-requirements.txt /build
WORKDIR /build
RUN pip3 install -r dev-requirements.txt
RUN git clone https://github.com/candlepin/subscription-manager.git
WORKDIR /build/subscription-manager
RUN python3 ./setup.py build
RUN python3 ./setup.py build_ext --inplace
