#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJ_DIR=$(dirname ${SCRIPT_DIR})

CONTAINER=$(podman create \
  -t test-subman:latest \
  /bin/bash --login -c "cd /subscription-manager && $*")
podman cp ${PROJ_DIR}/ ${CONTAINER}:/
podman start -ia ${CONTAINER}
podman rm ${CONTAINER}
