.TH SYSPURPOSE 8
.SH NAME
syspurpose \- Set the intended purpose for this system
.SH SYNOPSIS
.B syspurpose
[\fICOMMAND\fP] [\fIOPTION\fP]...

.SH DESCRIPTION
\fISyspurpose\fP is a utility for viewing and modifying system purpose
properties.
.PP
The properties (hints) set by \fIsyspurpose\fP are passed to a Red Hat
subscription management entitlement server (Customer Portal or Satellite 6) to
help attach the most appropriate subscriptions to the system automatically. The
entitlement server also reports whether the attached subscriptions match the
specified system purpose. Satisfying system purpose properties depends greatly
on the quantity, availability, and subscription SKU offerings that have been
purchased for the organization that the system is registered to.
.PP
The \fIset\fP, \fIunset\fP, \fIadd\fP, and \fIremove\fP subcommands modify the
local system purpose, and when possible will report the updated settings to the
Red Hat subscription management entitlement server (Customer Portal or Satellite
6).  The \fIshow\fP command displays the current system purpose.

.SH COMMANDS
.TP
\fBsyspurpose set-role \fIVALUE\fP\fP
Set the role property
.TP
\fBsyspurpose unset-role \fIVALUE\fP\fP
Clear the role property
.TP
\fBsyspurpose set-sla \fIVALUE\fP\fP
Set the service level agreement property
.TP
\fBsyspurpose unset-sla \fIVALUE\fP\fP
Clear the service level agreement property
.TP
\fBsyspurpose set-usage \fIVALUE\fP\fP
Set the system usage property
.TP
\fBsyspurpose unset-usage \fIVALUE\fP\fP
Clear the system usage property
.TP
\fBsyspurpose add-addons \fIVALUE\fP...\fP
Add values to the add-ons property
.TP
\fBsyspurpose remove-addons \fIVALUE\fP...\fP
Remove values from the add-ons property
.TP
\fBsyspurpose show \fIVALUE\fP\fP
Show the current system purpose properties
.SS Generic Commands
The following generic commands can be used as well
.TP
\fBsyspurpose set \fIPROPERTY\fP \fIVALUE\fP\fP
Set the value for a specific property. E.g. \fBsyspurpose set usage foo\fP is
functionally identical to \fBsyspurpose set-usage foo\fP.
.TP
\fBsyspurpose unset \fIPROPERTY\fP\fP
Clears the value for a specific property. E.g. \fBsyspurpose unset foo\fP is
functionally identical to \fBsyspurpose unset-usage\fP.
.TP
\fBsyspurpose add \fIPROPERTY\fP \fIVALUE\fP\fP
Add a value to a specific list property. E.g. \fBsyspurpose add addons foo
bar\fP is identical to \fBsyspurpose add-addons foo bar\fP.
.TP
\fBsyspurpose remove \fIPROPERTY\fP \fIVALUE\fP\fP
Clear a value from a specific list property. E.g. \fBsyspurpose remove addons
foo bar\fP is identical to \fBsyspurpose remove-addons foo bar\fP.

Only "addons" acts as a list property.  The other properties only accept a
single value.

.SH OPTIONS
.TP
\fB--help\fP
Display a summary of the available commands

.SH EXAMPLES
.TP
\fBsyspurpose set-role "RHEL Server"\fP
Indicate that this system should consume a RHEL Server subscription:
.TP
\fBsyspurpose unset-role\fP
Clear a previously set role

.SH BUGS
This tool is part of Red Hat Subscription Manager. To file bugs against this
command-line tool, go to <https://bugzilla.redhat.com>, and select Red Hat > Red
Hat Enterprise Linux > subscription-manager.

.SH AUTHOR
Chris Snyder <csnyder@redhat.com>

.SH COPYRIGHT
Copyright \(co 2018 Red Hat, Inc.
