---
- name: install cockpit
  package:
    name: cockpit
    state: present
  become: yes

- name: enable cockpit
  service:
    name: cockpit.socket
    enabled: yes
    state: started
  become: yes
