#!/bin/sh
set -eux

dnf install -y cockpit-ws python3-devel openssl-devel gcc

cd /var/tmp

tar -xzf subscription-manager.tar.gz --transform 's,[^/]*,/sm,'
cd sm
tar xzf ../subscription-manager-build-extra.tar.gz
python3 ./setup.py build
# Set $RPM_BUILD_ROOT to simulate a package build, so it works fine with the
# new Python changes in Fedora 36: https://bugzilla.redhat.com/2026979
RPM_BUILD_ROOT="/" python3 ./setup.py install --prefix /usr --root /

mv /usr/bin/{rhsm-facts-service,rhsm-service,rhsmcertd-worker} /usr/libexec
mv /usr/bin/subscription-manager /usr/sbin
