#!/usr/bin/env python
#
# Copyright (c) 2016 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation.
#
import dbus
import sys
import optparse

from subscription_manager import logutil
logutil.init_logger()

import rhsmlib.dbus as common

from rhsmlib import import_class
from rhsmlib.dbus.server import PrivateServer
from rhsmlib.dbus.objects import RegisterService

common.init_root_logger()


def main(args):
    bus_name = common.BUS_NAME

    if len(args) > 1:
        bus_name = args[0]

    object_classes = [
        RegisterService
    ]

    PrivateServer().run(
        object_classes=object_classes)
    return 0

if __name__ == "__main__":
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()
    sys.exit(main(args))
