#!/usr/bin/python

import sys

sys.path.append("/usr/share/rhsm")

from subscription_manager import logutil
logutil.init_logger()

from rhsmlib.dbus.services.subscriptions import server


def main(args):
    server.run()
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
